### ISSUE TITLE
Double-click on page doesn't commit recent changes

### ISSUE THREAD

**Issue by richardwonka** [Philip-Scott/Notes-up#106]
Hey there,

When switching to the view via the toggle buttons in the top bar, all changes get committed and the behaviour is as expected.

However, when switching from edit to view via double-click on the page's tab (between notebook list and editor/view pane) - the view does not show the most recent changes.

What a lovely little app you have put together there. :-)

**Comment by Philip-Scott** [comment]
Done! Fixed on: d306df2 :) 

I was loading the new page's data before saving the current page, thus the weird stuff was happening.

**Comment by richardwonka** [comment]
Nice! 

this looks like there are two places in the code that are _supposed_ to do the same thing (but didn't just now) - sounds like a target for refactoring. :)

Thank you for your work!
