### ISSUE TITLE
Internal links possible?

### ISSUE THREAD

**Issue by richardwonka** [Philip-Scott/Notes-up#107]
It would be great to be able to reference other pages by number (such as here #70) or name. 

A lot of note taking and general mind-work is networked in nature, so mapping the connections in the notes would be very helpful.

**Comment by Philip-Scott** [comment]
Fixed in c3dce25f3c0562b44fe1baf8807452dc203ec4b8. Adding links is now possible with the `<page #number text>` syntax, and you can get the link to the page from the UI :)
 
This feature will arrive in the new Notes-Up version
