### ISSUE TITLE
Doesn't start up in elementary OS 0.4 Loki

### ISSUE THREAD

**Issue by therocco** [Philip-Scott/Notes-up#109]
Trying to start the app causes it to crash immediately with this message:

```
** (Notes:13466): CRITICAL **: enotes_pages_list_load_pages: assertion 'notebook != NULL' failed
Segmentation fault (core dumped)
```

**Comment by Philip-Scott** [comment]
Hey, thank you for writing up this issue! 

How did you install the app btw? The issue you're having should've been fixed two days ago :sweat: 

https://github.com/Philip-Scott/Notes-up/blob/311f4e8ec7288566e322992ea32857d7dafff1f8/src/Widgets/PagesList.vala#L181

if you installed it via the PPA, try running your updates again. And if you build it manually, try pulling and recompiling. There was a new build made about an hour ago, so the update may not show right away. But please let me know if it works for you :)

**Comment by therocco** [comment]
Installed from PPA a couple days ago and deleted a notebook today and closed the app. I managed to fix it in dconf editor by setting `last-notebook` and `last-page` to `0`. Last notebook seemed to be the ID of the notebook I deleted right before closing.

**Comment by Philip-Scott** [comment]
Looks like it's fixed :) I can't reproduce it anymore on the latest version from AppCenter.

If you can still reproduce open this ticket again
