### ISSUE TITLE
Cannot properly align text highlighted as code

### ISSUE THREAD

**Issue by yerbestpal** [Philip-Scott/Notes-up#112]
I was hesitant to submit this as an issue as I am unsure whether this is a flaw or if I am doing something wrong. I am trying to format some text as code but when I do this, the code is no-longer on the appropriate lines and is sandwiched together. I've included before and after images.

Unformatted:
![no_code](https://cloud.githubusercontent.com/assets/15250241/25384950/2e25af3a-29ba-11e7-89ec-d98fbaa8217b.png)
Formatted:
![code](https://cloud.githubusercontent.com/assets/15250241/25384949/2e1f720a-29ba-11e7-9c6b-f2f13eabb674.png)

If this is down to me, just let me know.

**Comment by Philip-Scott** [comment]
@yerbestpal Hey man :) How are you doing the markdown code?

**Comment by Philip-Scott** [comment]
Typing:

 ![screenshot from 2017-04-25 07 52 34](https://cloud.githubusercontent.com/assets/10786508/25386200/67289b1a-297b-11e7-974f-328035650cbb.png)

should return this:
![screenshot from 2017-04-25 07 52 11](https://cloud.githubusercontent.com/assets/10786508/25386215/73e0ae6a-297b-11e7-9d2e-919c23bcf745.png)

Make sure you add a blank line before the firest ` ``` ` so that Markdown doesn't think you're typing on the same paragraph :)

**Comment by yerbestpal** [comment]
That's a great help, thanks.

**Comment by Philip-Scott** [comment]
No problem! :) 

I see you're using python! If you type `<highlight>` on one line, and do your code like this:

![screenshot from 2017-04-25 17 40 03](https://cloud.githubusercontent.com/assets/10786508/25410769/96053054-29cd-11e7-8db4-c7a9b89e3724.png)


The syntax will automatically be highlighted :) 

![screenshot from 2017-04-25 17 39 48](https://cloud.githubusercontent.com/assets/10786508/25410780/ad656732-29cd-11e7-9cd4-b182fb2151a4.png)

Good luck learning man! Keep it up :)

**Comment by yerbestpal** [comment]
Hrm, can't seem to get this to work at all. I'll keep messing around. Thanks though.

**Comment by yerbestpal** [comment]
From what I can tell I'm doing this correctly, but the python highlighting isn't working. 

view mode:
![view](https://cloud.githubusercontent.com/assets/15250241/25439399/46b4411c-2a94-11e7-9320-7dc7958b493a.png)

edit mode:
![edit](https://cloud.githubusercontent.com/assets/15250241/25439408/4cd225e6-2a94-11e7-8b22-c21a18e271ee.png)

Also I'm aware I'm dragging this out in an irrelevant Github issue. If you'd rather I emailed you I'll do that. Thanks for the help!

**Comment by Philip-Scott** [comment]
It's no problem :) Do you have the newest version installed? If you do, you should be able to see a help button on the top right that clicking it shows something like this:

![screenshot from 2017-04-26 10 24 45](https://cloud.githubusercontent.com/assets/10786508/25442567/3dd0fafc-2a5a-11e7-9855-8bff027c58b9.png)

If you do, can you make sure that the folder `/usr/share/notes-up/` exists on your computer, and show me it's contents?

**Comment by Philip-Scott** [comment]
And if you DO have it installed, could you try testing the code with highlight on it's own page? :)

**Comment by yerbestpal** [comment]
It looks like I'm out of date then. I have installed via the PPA. Also, I don't have `/usr/share/notes-up/`.

**Comment by yerbestpal** [comment]
It looks like I'm out of date then. I have installed via the PPA. Also, I don't have `/usr/share/notes-up/`.
