### ISSUE TITLE
When deleting notes, I have to restart the app for the note to disappear from the list.

### ISSUE THREAD

**Issue by yerbestpal** [Philip-Scott/Notes-up#116]
Even though there is visual confirmation of deletion via the trash section, the note remains listed and it can cause confusion unless I restart the app.

**Comment by Philip-Scott** [comment]
It was actually by design to not hide the notes (Although they can't be edited once they're in the trash) But yeah, i think it does make more sense to just remove it from the list as well

**Comment by Philip-Scott** [comment]
Closing, i've made it so they're insensitive now in the list :)
