### ISSUE TITLE
Problems with cmake 3.8

### ISSUE THREAD

**Issue by malnvenshorn** [Philip-Scott/Notes-up#119]
Trying to build the app from source fails with cmake 3.8. Using cmake in version 3.7.2 works.

Here is the output:

```
-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for one of the modules 'webkit2gtk-4.0;webkit2gtk-3.0'
-- Checking for modules 'granite>=0.3;gtksourceview-3.0>=3.10;gthread-2.0;gtk+-3.0>=3.9.10;sqlite3>=3.5.9'
--   Found granite, version 0.4.0.1
--   Found gtksourceview-3.0, version 3.24.1
--   Found gthread-2.0, version 2.52.1
--   Found gtk+-3.0, version 3.22.12
--   Found sqlite3, version 3.18.0
-- Checking for modules 'granite>=0.3;gee-0.8;gtksourceview-3.0;gtk+-3.0;webkit2gtk-4.0;sqlite3>=3.5.9;discount'
--   No package 'discount' found
CMake Error at /usr/share/cmake-3.8/Modules/FindPkgConfig.cmake:416 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.8/Modules/FindPkgConfig.cmake:589 (_pkg_check_modules_internal)
  CMakeLists.txt:67 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
```

**Comment by Philip-Scott** [comment]
Weird that's failing at `discount` since that's a dependency i ship with Notes-Up.... I can't really fix that atm since my version of CMake is 3.5.1

**Comment by memnoth** [comment]
``sudo apt update && sudo apt install -y libmarkdown2-dev`` will help you to completely compile it.
discount is a program/library about `implementation of the Markdown markup language in C`.
But actually we need **libmarkdown2-dev**, not `discount` from package.

P.s i don't know why this package is needed to compile it, even thought it isn't linked in run-time aspect.

**Comment by demonpig** [comment]
@malnvenshorn what operating system are you using? I can boot up a VM and test this out.

**Comment by memnoth** [comment]
Have you tried to install ``discount`` ?

**Comment by malnvenshorn** [comment]
@demonpig I'm using Arch Linux.

By providing `libmarkdown.so` Notes-Up will compile. It just fails with the current cmake version and the shipped dependency.

**Comment by demonpig** [comment]
@malnvenshorn thanks!

**Comment by JamesTiberiusKirk** [comment]
Hi, I'm on arch and I do have discount installed, but it still fails.

**Comment by malnvenshorn** [comment]
Sorry you are right. Downgraded to cmake 3.7.2 and forgot to upgrade again before testing. My mistake...

**Comment by Philip-Scott** [comment]
@malnvenshorn, do you think that the problem is that CMAKE 3.8 is not picking up the internal package anymore?

**Comment by demonpig** [comment]
I have not quite nailed down what exactly is the issue. But I did discover if I removed the following [line](https://github.com/Philip-Scott/Notes-up/blob/master/CMakeLists.txt#L54), I was able to compile and run the program. This was tested with Antergos and CMake 3.8.0. I will continue to look into the issue this week.

**Comment by Mailaender** [comment]
Is it possible to use an external discount or libmarkdown instead of bundling it?

**Comment by demonpig** [comment]
I have an open [pull request](https://github.com/Philip-Scott/Notes-up/pull/123) where discount is added as an git submodule instead of being bundled with the Notes-up source code.

Outside of that, I don't think it is going to hurt anything. Will have to change the deb packaging config and the CMakefile.
