### ISSUE TITLE
Wrong icon size with headerbar button with Ubuntu

### ISSUE THREAD

**Issue by khurshid-alam** [Philip-Scott/Notes-up#122]
I am using it on Ubuntu 17.04, granite-3.1.x installed from elementary PPA. Icon theme is default icon theme `ubuntu-mono-dark`and gtk-theme Numix.

Somehow it sets icon-size to a uncommon number **6**.. You can see it with gtk-inspector

![notes-up-bug-iconsize](https://cloud.githubusercontent.com/assets/1333217/25770926/365fa33c-3260-11e7-8f56-40bb574489af.png)

The result is same with every other gtk/icon theme including Adwaita.

**Comment by demonpig** [comment]
@khurshid-alam can you re-build Notes-Up with the new updates that were pushed to master branch? If you are still experiencing the issue, can you post some new photos? Thanks!

**Comment by khurshid-alam** [comment]
@demonpig 

Thanks. It fixed the issue. But ideally it shouldn't request `non-starred.svg` on headerbar. It should request `non-starred-symbolic.svg` (example dconf). Then it will match properly with the theme whether dark or light.
