### ISSUE TITLE
Feature Request: Export / Save whole notebook

### ISSUE THREAD

**Issue by blixuk** [Philip-Scott/Notes-up#131]
It would be awesome to export / save a whole note book or it's sections. 
That way you can break notes up and then have them all together when they need to be shared.
Saving them as an epub and being able to export them as markdown files.

**Comment by Philip-Scott** [comment]
Closing since it's a dup of: #113 :) 

But yes, it's coming: 
https://github.com/Philip-Scott/Notes-up/projects
