### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by snowparrot** [Philip-Scott/Notes-up#132]
After 10 minutes I cant enable syntax highlighting so I assume Notes-Up needs better documentation for its features.

P.S.: Can someone give me an example to activate syntax highlighting?

**Comment by fppaess** [comment]
![screenshot from 2017-07-14 21 02 05](https://user-images.githubusercontent.com/12243928/28234595-c558d38a-68d7-11e7-9e22-7956ce67484f.png)
![screenshot from 2017-07-14 21 02 21](https://user-images.githubusercontent.com/12243928/28234594-c556ad08-68d7-11e7-99af-5767cd06781c.png)

**Comment by Philip-Scott** [comment]
There's also a help button where you can access the features it has in the Edit View's toolbar
