### ISSUE TITLE
no support of Java in syntax highlighting

### ISSUE THREAD

**Issue by snowparrot** [Philip-Scott/Notes-up#133]
The following code doesnt activate syntax highlighting:

if  (cursor.moveToFirst()){
   do{
      String data = cursor.getString(cursor.getColumnIndex("data"));
      // do what ever you want here
   }while(cursor.moveToNext());
}
cursor.close();

Edit: Of course I put highlight, ´´´java etc. around the code but if I do in github it sees my example as code :P

**Comment by snowparrot** [comment]
@Philip-Scott Hey, maybe a better bug solution. Neither "java" nor "Java" are supported. You can the header of the bug report.

**Comment by Philip-Scott** [comment]
Interesting. I just pulled a new version of [Highlight JS](https://highlightjs.org/download/) while making sure Java was selected, and it also didn't work :disappointed: It's probably a problem with Highlight Js + Webkit like #115 

For now, try using `c` or `c++` as the language name.

Closing this as a Duplicate of #115
