### ISSUE TITLE
Question: Is there a way to manually back up your entire notbook or selected notes?

### ISSUE THREAD

**Issue by proxycyber** [Philip-Scott/Notes-up#137]
Is there a way to manually create a backup file of all of your notes and notebooks? Really important to me.

**Comment by Philip-Scott** [comment]
the whole database is stored on `/home/YOURNAME/.local/share/notes-up/NotesUp.db` Currently there isn't a way to export your selection, but i want to work on that during this summer :) 

This is the Notes Management Project https://github.com/Philip-Scott/Notes-up/projects/2

**Comment by Philip-Scott** [comment]
Closing in favor of #113
