### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by voline** [Philip-Scott/Notes-up#14]
Well, I think I have complained enough, here is a contribution. Make your pick for the icon;

![image](https://cloud.githubusercontent.com/assets/17718635/13712047/9049a61e-e7e7-11e5-9ab0-350ef9a706d5.png)

I am using the rightmost for myself at the moment. Looks more playful.

**Comment by Philip-Scott** [comment]
To be honest, im not a big fan of them :P The current default icon says a bit more about what the app is about (A notebook :wink:) I was thinking about adding a markdown "mark" on the notebook, but i find that i like more the minimalistic look it currently has

But thank you very much still :)
