### ISSUE TITLE
Redundant Notes icon in applications menu

### ISSUE THREAD

**Issue by harisvsulaiman** [Philip-Scott/Notes-up#141]
![image](https://user-images.githubusercontent.com/29329325/27994307-bedffc8e-64d8-11e7-84c6-60eff98bebdd.png)

**Comment by Philip-Scott** [comment]
You might have compiled an older version of notes-up before :) The one on AppCenter changed the name of the .desktop file. 

Try removing that icon with `rm /usr/share/applications/notes.desktop` or notes-up or something like that... don't remember the exact name off the top of my head

**Comment by harisvsulaiman** [comment]
@Philip-Scott No,I did not compile notes up myself. Uninstalling notes up from app center and restarting wing panel got rid of the redundant icon.

There is no .desktop file at  `rm /usr/share/applications/notes.desktop`

**Comment by Philip-Scott** [comment]
Maybe you just had an older version from before the change :) But glad it's gone
