### ISSUE TITLE
Where do we find the Plugins configuration?

### ISSUE THREAD

**Issue by kostrykin** [Philip-Scott/Notes-up#142]
Obviously, at least from version 1.3.1 on, plugins appear to be available. I am using version 1.4.3. But where do we find the Plugins configuration? I mean, where are they enabled, disabled or just listed? There is no such point in the settings menu of Notes-up.

**Comment by Philip-Scott** [comment]
All plugins are enabled by default, and there's actually no configuration needed. They will just get loaded when you use them.

You can see how to use them by opening the Help sidebar, or some plugs even have a button on the toolbar such as the Color and the Page Break items :)

![screenshot from 2017-07-11 07 14 32](https://user-images.githubusercontent.com/10786508/28067854-9f79feae-6608-11e7-9fc9-4ff2d760dfab.png)
