### ISSUE TITLE
Backup help needed

### ISSUE THREAD

**Issue by JamesTiberiusKirk** [Philip-Scott/Notes-up#143]
Hi, 
I know that you are about to implement a import/export feature, however, I need a quick and dirty fix right now. I am about to swap my laptop and I was wondering if there is a way to just backup a database file of some sort then throw it onto the new laptop.

Thanks in advance.

**Comment by Philip-Scott** [comment]
Hey! :)

Depending on when you first installed the app, the database is located in either `~/.local/share/notes-up/` or `~/.local/` and it's named NotesUp.db.

You should be able to copy that file, and add it to `~/.local/share/notes-up/NotesUp.db` on your new machine.

Feel free to ask if you have any questions!

**Comment by JamesTiberiusKirk** [comment]
Thanks a lot!!
Found it in ~/.local/share/notes-up/

**Comment by JamesTiberiusKirk** [comment]
Maybe make the db file location be an option in preferences.
It would be cool if i could place it inside my documents folder which is constantly being synced to my nextcoud server.

**Comment by Philip-Scott** [comment]
You can change that value yourself by opening dconf. It's located in org > notes > notes-database :)

**Comment by JamesTiberiusKirk** [comment]
Again, thanks a lot!

**Comment by Philip-Scott** [comment]
Any time :)
