### ISSUE TITLE
Can I delete Pages within a Notebook?

### ISSUE THREAD

**Issue by worldofpeace** [Philip-Scott/Notes-up#144]
#### I currently can not find a way to do so. I only see functionality to delete notebooks not pages within notebooks.

My natural inclination is to right click a page and see a delete option.

**Comment by Philip-Scott** [comment]
You can only delete pages in Edit mode. That way you can't accidentally remove them while viewing them :)

![screenshot from 2017-07-19 10 39 18](https://user-images.githubusercontent.com/10786508/28375961-88c3ae6e-6c6e-11e7-94d0-d2c550cda75c.png)

**Comment by worldofpeace** [comment]
Makes a lot of sense to have it there because of the workflow you have created.
You have the best apps in appcenter hands down. :+1:
