### ISSUE TITLE
Can't find a way to back up notes

### ISSUE THREAD

**Issue by proxycyber** [Philip-Scott/Notes-up#148]
Is there a way to backup notes? Not individual notes, but is there a backup file that we can manually export so that let's say we export notes from date x to date y, we go on another computer, install Notes-up and import that backup file so all notes stay intact? 

Or is there a database file that we can backup without it getting corrupt? I believe I tried it once and when putting it back, it was unreadable.

I remember posting a while back and seeing that this isn't possible yet, but just curious if there's any updates.

**Comment by Philip-Scott** [comment]
Check this out: https://github.com/Philip-Scott/Notes-up/issues/143

But yeah, i think i'll add a way to open the folder where it's located, and be able to change it

Coping and pasting that file shouldn't cause a problem though

**Comment by proxycyber** [comment]
Thanks, @Philip-Scott! :+1: So, can you please let me know if this counts?

I copied the **.notes-up.db** file from /local/share/Notes-up to my home folder. Uninstalled Notes-up, re-installed it. No notes saved. Copied the database file I saved on my Home folder to the local Notes-up folder and all notes stay back! This makes me happy, but I wonder if it'd work if I backed that file up to the cloud every so often. In addition, this may sound like a silly question, will the images in the notes back up if those images aren't locally stored on my new hard drive? Or are they stored in the Db file as well?

**Comment by Philip-Scott** [comment]
New images are stored on the DB file now :) If in the edit mode, the "image" looks something like: `<image 1>` it means that it's stored on the database. If not, it's because it was added in drag and drop, or before storing images was implemented.

As long as you don't use the app on multiple computers at the same time, or before it syncs you won't have a problem :)

**Comment by proxycyber** [comment]
@Philip-Scott, nice, thank you! This is seriously the best tool in the history of the universe. I'm going to try to tell more people about it. I came to Elementary just to use this tool. Can't wait to see its growth, thanks for the hard work!

Oh, no, I don't use sync features usually, would just download them locally. I only use one machine, so was just using that as an example in case my hard drive crashed and I needed the db. file. Thanks again!
