### ISSUE TITLE
Selected text not highlighted when using one of the Quilter themes

### ISSUE THREAD

**Issue by LievenHanssen** [Philip-Scott/Notes-up#149]
When in one of the Quilter themes, either _Quilter_ or _Quilter Dark_, selected text won't be highlighted. In any of the other themes, this is not the case, selected text is highlight like it usually is. 
In the program Quilter itself I can't seem to reproduce this bug. I've made a [short video](https://youtu.be/n7YHB8arbM8) which you can watch to see how the different themes affect the highlighting of selected text in Notes-up.

**Comment by Philip-Scott** [comment]
This is a problem with Quilter, and the custom styles it's using. (The Quilter theme also doesn't work in Scratch-text editor for example)

Please report it there :) Thanks!
