### ISSUE TITLE
pdf export creates empty file

### ISSUE THREAD

**Issue by snowparrot** [Philip-Scott/Notes-up#150]
Following text creates an empty pdf file during export:

Couchsurfingtext

Hey, my name is Yuny from Germany. I'm 22 years old and a math student.

**Comment by Philip-Scott** [comment]
To get this to work on your language, i need your help :) Can you follow what this says, and send me a screenshot of your print dialog? Thanks!

https://github.com/Philip-Scott/Notes-up/issues/1#issuecomment-313936098

**Comment by onirica** [comment]
I just committed a change that solves the issue for german desktops - because I had the same problem. Just three lines in the translation file do the trick.

**Comment by Philip-Scott** [comment]
Yup :) Thank you very much!
