### ISSUE TITLE
Feature Request: Change Font Size

### ISSUE THREAD

**Issue by proxycyber** [Philip-Scott/Notes-up#153]
I think it'd be useful if we could change font size or at least font spacing. The whole thing seems too centered, I'd like to use up more width and less length in a note.

**Comment by Philip-Scott** [comment]
the way Markdown works is by using CSS to style your notes. You can modify this "stylesheet" per notebook¸ or for the whole app by either opening the notebook's preferences or the app's, and going to the style section.

Here, you put the style rules you want, so if you wanted your paragraphs with a font size of 16px, it would look like:

![screenshot from 2017-07-31 10 44 36](https://user-images.githubusercontent.com/10786508/28785892-450e74b0-75dd-11e7-98d0-555142a7bb00.png)

See https://www.w3schools.com/css/css_font.asp for more details :)

**Comment by proxycyber** [comment]
Thanks! :+1:

**Comment by Philip-Scott** [comment]
No problem :)

**Comment by JamesTiberiusKirk** [comment]
Where would I find a list of all of the other tags such as tor titles, lists and other elements?
Because using just "p" only changes the normal written text.

**Comment by Philip-Scott** [comment]
@JamesTiberiusKirk It's normal HTML, it uses tags such as h1 for titles. h2 for `##` etc. You can check https://www.w3schools.com/html/html_elements.asp for more info :)
