### ISSUE TITLE
Could I please get some help with installing this on Ubuntu 17.04

### ISSUE THREAD

**Issue by JamesTiberiusKirk** [Philip-Scott/Notes-up#154]
Hi, I just switched to Ubuntu Gnome 17.04, and this application is just way to damn useful to give up.
**I have tried:** 
- Installing from the PPA
the PPA 404s
- Downloading .deb from the PPA
It tells me I don't have libgranite3 and I have not found a way to install it.
output:
https://pastebin.com/2xtzipgb
- Compiling from source
output:
https://pastebin.com/U79wycA4
log file:
https://pastebin.com/s5cynKi5

I really like this application and wish I could still use it, especially since all of my notes are in the backed up db file.

Any help will be greatly appreciated.

Update:
U just noticed that Notes appeared in the application menu, when I try to run it from terminal I get this.
`notes-up: error while loading shared libraries: libgranite.so.3: cannot open shared object file: No such file or directory`

**Comment by kostrykin** [comment]
There [appears to be a build of libgranite for 17.04](https://launchpad.net/granite/+packages) though I cannot find any PPA which provides it. Still, you should be able to download and install it manually.

**Comment by Philip-Scott** [comment]
@JamesTiberiusKirk Try compiling libgranite from source :) https://github.com/elementary/granite/

**Comment by JamesTiberiusKirk** [comment]
Just did that, it still kicks off the same errors.

**Comment by kostrykin** [comment]
You installed it after compiling?

**Comment by JamesTiberiusKirk** [comment]
Yeah, the app got removed after this.
`sudo apt-get install --fix-broken`
Then tried to reinstall Notes-up with the deb and to compile it from source. Same story.

**Comment by Philip-Scott** [comment]
delete the build directory, and type `-Dnoele=1`  after cmake :) 
you're going to have to compile it yourself, are you sure you have installed all the other dependencies?

**Comment by demonpig** [comment]
@JamesTiberiusKirk The following is a script that I wrote to build Notes-up on Ubuntu 17.04 (Unity DE not Gnome DE).
```
#!/bin/bash
#
# build-notes-up.sh
# Date: 2017-07-26

# This script is used to build Notes-up on Ubuntu 17.04. It can probably be
# used to build the application on other Ubuntu versions.

# Global Variables
NOTESUP_DIRNAME="Notes-up"

# Global Functions
function runapp(){
  CURRENT_DIRECTORY="$(dirname $0)"
  GSETTINGS_SCHEMA_DIR=${CURRENT_DIRECTORY}/${NOTESUP_DIRNAME}/build/usr/share/glib-2.0/schemas/ ${CURRENT_DIRECTORY}/${NOTESUP_DIRNAME}/build/usr/bin/notes-up
}

if [[ "$1" == "--run" ]]; then
  runapp
  exit 0
fi

# Build tools
sudo apt install cmake valac git

# Required Libraries
sudo apt install libwebkit2gtk-4.0-dev libgee-0.8-dev libgtksourceview-3.0-dev libgtk-3-dev libgranite-dev libsqlite3-dev libglib2.0-dev

# Clone the directory
git clone https://github.com/Philip-Scott/Notes-up.git "${NOTESUP_DIRNAME}"

# Build the application
cd "${NOTESUP_DIRNAME}"
mkdir build
cd build

cmake -Dnoele=1 -DCMAKE_INSTALL_PREFIX=usr/ ..
make
make install
```

To run the application, just run the following command:
`./build-notes-up.sh --run`

Please just use this script as a reference.

**Comment by JamesTiberiusKirk** [comment]
@Philip-Scott `-Dnoele=1` after worked, thanks a lot!

@demonpig  Your script works on Ubuntu Gnome too, there should be no difference anyway.

**Comment by onirica** [comment]
There should be no need to compile granite for Ubuntu 17.04. There is a package libgranite-common (0.3.0) and also libgranite-dev (if you want to compile) in the universe repository. You probably just need to activate the repository and reload the package list. 

Installing Notes-Up on Ubuntu 17.04 is not the problem. But it doesn't run as long as contractor isn't installed and this one is missing in the repositories. I tried installing the deb-package for 16.04 (xenial) from https://launchpad.net/~elementary-os/+archive/ubuntu/stable/+packages and it worked. I wouldn't recommend adding the repository though.

**Comment by Philip-Scott** [comment]
@onirica Compiling with the `-Dnoele=1` disables the elementary OS only features like contractor, so if you compile it with that flag you will be able to run it outside of the elementary ecosystem :) 

I'm keeping this issue open for now until i add a wiki entry about building on another distro. If @demonpig doesn't mind i'm to use his script there

**Comment by onirica** [comment]
That is really good to know! Will try that.

**Comment by JamesTiberiusKirk** [comment]
@Philip-Scott What exactly is this contractor anyway?
And is `-Dnoele=1` a universal thing for elementary os apps?
Because there's also some other slick software in there that would be useful.

**Comment by Philip-Scott** [comment]
@JamesTiberiusKirk No, that's just a thing for Notes-Up atm. Contractor allows for file-sharing within applications. For example: elementary's mail app has a contract for sending a file in an email, and any app can access that functionality very easily.

Everything bellow the gray line are contracts on my machine that are working with Notes-Up :) 

![screenshot from 2017-07-28 11 01 20](https://user-images.githubusercontent.com/10786508/28725801-37fbfd70-7384-11e7-8e89-f650e467186e.png)

**Comment by JamesTiberiusKirk** [comment]
ah! ok i see

**Comment by Philip-Scott** [comment]
I added @demonpig's script on https://github.com/Philip-Scott/Notes-up/wiki/Build-and-Install-on-Ubuntu-17.04, so i'm going to close this for now :)
