### ISSUE TITLE
File Storage?

### ISSUE THREAD

**Issue by OriginalFannibal** [Philip-Scott/Notes-up#157]
Where exactly are the files stored locally? I would like to be able to backup my notes and even import them back in, in case I switch systems or reinstall.

**Comment by OriginalFannibal** [comment]
Sorry about not checking closed issues before opening this one. Found the answer :)

**Comment by Philip-Scott** [comment]
Thank you for closing it once you found it :) You're a great person! 

But yeah, i wanna add a way to open Files into the folder it's located. I'm planning on working a couple of things, but working out the UX first

**Comment by OriginalFannibal** [comment]
Haha, thanks :)  
But seriously, thank you so much for this amazing app! I love it so much!
