### ISSUE TITLE
Support for a folder structure

### ISSUE THREAD

**Issue by OriginalFannibal** [Philip-Scott/Notes-up#158]
I don't know if this is part of the import/export feature that is in the works but could it be possible to offer a directory mode where you open a directory with it and all its subdirectories acting as notebooks and sections?  

That's how I had things set up on Atom and it is an immensely portable setup, even for systems where I cannot have access to Notes Up. What I am asking is if the database that is currently stored in the form of a `.db` file be stored in the form of a folder with the notebooks being directories within it and the sections being directories within that so that one could just copy that base folder and use it with any app on any system?

**Comment by Philip-Scott** [comment]
That's actually how it used to work before, but sadly it's management it was not very scalable for when you had many notes. (And things like moving was much more dangerous and destructive, as files with the same name got deleted) And now with the database i'm also storing things such as the creation and modification date, as well as stylesheets per notebook and many other things like images you import and a cache so your pages get displayed faster.

Maybe i can later make it so you can open .md files with the Notes-Up viewer & editor :)

**Comment by OriginalFannibal** [comment]
> Maybe i can later make it so you can open .md files with the Notes-Up viewer & editor :)  

That would be amazing!

**Comment by Philip-Scott** [comment]
Yeah, i have quite a bit of plans, i just need time :disappointed: 

Right now i've been working on making [Spice-Up](https://github.com/Philip-Scott/Spice-up) more feature complete since Notes-Up is pretty good atm :)

**Comment by OriginalFannibal** [comment]
I know this isn't really the place for a conversation but I needed to say this. You've been doing an absolutely phenomenal work. Take all the time you need. It's worth it :)
