### ISSUE TITLE
Sort Pages List

### ISSUE THREAD

**Issue by Philip-Scott** [Philip-Scott/Notes-up#16]
Select whether to sort pages via:

- [ ] Alphabetical
- [x] Creation Date (Current)
- [ ] Modification Date

**Comment by theranger** [comment]
Why not having an UI control or settings option to select desired sorting behavior?

**Comment by Philip-Scott** [comment]
After some thought, i'm not doing this. I really don't want to keep adding settings, and i feel like it wouldn't be much benefit since we already have the search
