### ISSUE TITLE
Search Within A Note

### ISSUE THREAD

**Issue by lokesh-krishna** [Philip-Scott/Notes-up#160]
So sorry about opening so many issues :see_no_evil: 

Could it be possible to implement the kind of searching within notes that we use in browsers? Highlighting each occurrence of a term within the note and letting you cycle between them by using the Enter key or something along those lines.

**Comment by proxycyber** [comment]
Agreed! Would be useful.

**Comment by Philip-Scott** [comment]
Fixed in 57bc80a. Searching now highlights the word that was being search for in the viewer :+1:
