### ISSUE TITLE
Request: Don't Show Markdown in List Preview

### ISSUE THREAD

**Issue by proxycyber** [Philip-Scott/Notes-up#161]
You know how there's a left column that has a list of all entries? I really wish that, for example, the first line of my actual entry was a header, the preview in the item list did not show #*** and so on. I just think it makes it seem more messy, to be honest and I love this app overall, I just wish there was an option to remove that markdown symbols from the preview. If it's not in the entry when you view it, it shouldn't be in the list view, either.

Another cool thing would be is to be able to disable list view synopsis, so it's a list of titles rather than a title and the first few lines of the body.

**Comment by OriginalFannibal** [comment]
> Another cool thing would be is to be able to disable list view synopsis, so it's a list of titles rather than a title and the first few lines of the body.  

Simplenote offers this option in the form of a condensed view. I was considering opening a separate issue for it. @Philip-Scott Do you recommend opening a separate issue for that or will this one suffice?

**Comment by Philip-Scott** [comment]
@OriginalFannibal What Proxy said about the markdown _is/could be_ a bug, but about having a "condensed view"... I don't know if i would want to have that as an option.

Basically: 
>  [Don't ever ask users to make engineering or design decisions.](https://elementary.io/docs/human-interface-guidelines#avoid-configuration )

Maybe there could be a way to edit it instead, or get the preview in a smarter way instead of the second line

**Comment by Philip-Scott** [comment]
Fixed in 2e3bc7f
