### ISSUE TITLE
Can't find a way to insert videos

### ISSUE THREAD

**Issue by proxycyber** [Philip-Scott/Notes-up#164]
If I understand correctly, the Plugins project has to do with Notes-up? If so, how can I configure these things? For example, inserting a video.

**Comment by dcharles525** [comment]
You use to be able to insert an Youtube video but i don't know where the option went. It seems to be disable for the moment.

**Comment by Philip-Scott** [comment]
Yup :) It's all in the help area. All available plugins are enabled, and are only loaded when you actually use them

`<youtube [Link]>` without the `[]` of course ;)
