### ISSUE TITLE
1.4.7 not opening after installing from elementary appcenter

### ISSUE THREAD

**Issue by ultraviolet-1986** [Philip-Scott/Notes-up#168]
Upon installing this and finding it not responsive, I tried the command 'notes-up' and it output the following:

**[INFO 08:33:05.383417] Application.vala:153: Notes-Up version: 1.3
[INFO 08:33:05.383449] Application.vala:155: Kernel version: 4.10.0-32-generic
**
ERROR:/build/com.github.philip-scott.notes-up-1.4.7/src/Services/DatabaseTable.vala:73:database_table_prepare_db: assertion failed: (res == Sqlite.OK)
Aborted (core dumped)**

May be a missing dependency on install, thanks - love the app!

**Comment by Philip-Scott** [comment]
Just to be sure, The command is not notes-up, is `com.github.philip-scott.notes-up`. did you add the PPA?

**Comment by ultraviolet-1986** [comment]
Hi, no I didn't add the PPA - I just checked `software-properties-gtk` to check and there is no PPA present. I installed it using the elementary appcenter > office > curated apps section. The command you gave me above says `com.github.philip-scott.notes-up: command not found`. Thanks, and sorry for taking so long to respond.

**Comment by Philip-Scott** [comment]
Did you used to use Notes-Up before? It appears to be failing on database creation: looks like it can't create a file on /home/your-user/.local/share/notes-up/, or it doesn't have permissions. Can you check that for me? :) Thanks

**Comment by ultraviolet-1986** [comment]
Hi, you're right - creating the folder in this location fixed this. My install was getting heavy so I uninstalled everything but the base apps and removed configs, cache and files manually to reinstall the apps I use fresh without having to re-image the machine.

So it was my bad, sorry ^_^b

Looks like this can be closed, but it should have permission to create the directory and database, but like I said - this is an old install so my permissions may be a little off. I'll try another machine to make sure this is just me.

Thanks!

**Comment by ultraviolet-1986** [comment]
Hi, just tested another machine and also a VM and it starts without an issue - setting this as closed. Looks like I broke something before. Thanks again!

**Comment by Philip-Scott** [comment]
No problems :) Glad you got it fixed!

**Comment by YujiSaeki** [comment]
I had the same issue with ~/.local/share/notes-up/ not existing. Perhaps display a message asking users to either create the folder? I'd suggest having Notes-Up create the folder, but I recall Flatpak sandboxes everything to the point of frustration for many devs.
