### ISSUE TITLE
Any plans to introduce a tagging feature?

### ISSUE THREAD

**Issue by proxycyber** [Philip-Scott/Notes-up#169]
Are there any plans to introduce a tagging feature for notes?

**Comment by jtrees** [comment]
This is the feature I am waiting for before I start to use this app.

**Comment by Philip-Scott** [comment]
New tagging system has been added. Now notes from different notebooks can share a tag and you can now load all pages from a tag as if it was a notebook. Coming soon in version 2.0.0

## Sneak Peak of version 2.0.0

![image](https://user-images.githubusercontent.com/10786508/54652054-0d889b00-4a7b-11e9-8db8-cfc32e9049b1.png)
