### ISSUE TITLE
Feature Request : Save the image in the database

### ISSUE THREAD

**Issue by ar0ra1** [Philip-Scott/Notes-up#174]
It becomes messy managing the screen shots and images, and sometimes they get deleted.
Could you possibly add the feature to save the image in the database (blob)

Would be really useful!

**Comment by Philip-Scott** [comment]
That's already the case. If you click on the image button on the editor, the file you pick will get saved to the database, and something like `<image 1>` will appear :)

If you don't have that, you might need to run updates or install the correct package if you Installed it from the PPA ;) check the instructions on the readme

**Comment by ar0ra1** [comment]
Oh my bad!
I was using the markdown way to add the image 
![]()
