### ISSUE TITLE
change dconf location

### ISSUE THREAD

**Issue by snowparrot** [Philip-Scott/Notes-up#177]
As "org.notes" is very generic location for dconf there should be another name like "com.github.philip-scott.notes-up".

**Comment by Philip-Scott** [comment]
It can't be changed though since for people who already have the app and the database is stored in a different location could loose those changes.

**Comment by snowparrot** [comment]
Im not sure how flexible the dconf api is but can it just check both "org.notes" and "com.github.philip-scott.notes-up" ?

**Comment by Philip-Scott** [comment]
I'd have to include both anyways. If i don't include the Schema, the data will be destroyed when it's updated

**Comment by snowparrot** [comment]
so it is possible?

**Comment by Philip-Scott** [comment]
Yes, but `org.notes` would still be in use so there's really no point in doing the switch
