### ISSUE TITLE
Inconsistencies between editing and actual markdown

### ISSUE THREAD

**Issue by danybeam** [Philip-Scott/Notes-up#181]
When using * as a symbol and not to make words in *italic* there is a small inconsistence between what the editor view tells and the markdown view shows (please see attached files)
![report 1](https://user-images.githubusercontent.com/9967540/30040554-62c28e80-91a6-11e7-9390-a9588bdc373d.png)
![report 2](https://user-images.githubusercontent.com/9967540/30040555-62c44022-91a6-11e7-9da6-d07423e1e8b6.png)

**Comment by Philip-Scott** [comment]
Looks like this is a problem with the SourceView implementation. If you run `\*` does it keep the * in place?

**Comment by danybeam** [comment]
if I put `\*` it does keep de `*` in place

**Comment by Philip-Scott** [comment]
Ahh yeah, it's normal behavior then. The markdown is taking your `*` and using them as if you meant to make the text italics. You can also use ` to mark something that contains asterisks without it turning into italics 

Closing the report :)
