### ISSUE TITLE
Notes-Up needs a lot energy

### ISSUE THREAD

**Issue by snowparrot** [Philip-Scott/Notes-up#183]
If you open the Notes-Up window the battery status icon on the above-right corner complains too much energy even you dont do anything.

Apps like Android Studio uses less energy (if you believe the battery applet) but far more complicated.

**Comment by Philip-Scott** [comment]
if you run `htop` what's the CPU % that Notes-Up is taking?

It should only be doing work when you switch between View and Edit, or view new pages since it needs to render them

**Comment by snowparrot** [comment]
I suppose after changing the window it becomes 20 % for a small time. 10 % during Scrolling. 5 % during writing. Changing the page 6 %.

**Comment by Philip-Scott** [comment]
Yeah, this is normal because of the process that's loading & rendering the content since it's a WebView. The CUP usage should not be near as high on idle though. Can you confirm that?

**Comment by snowparrot** [comment]
idle as defined as doing nothing in Notes-Up is very low.

**Comment by Philip-Scott** [comment]
That's good then! In this case this is normal behavior since it needs to process things in order to show the information :)
