### ISSUE TITLE
Cancel pdf export create a file

### ISSUE THREAD

**Issue by dabou** [Philip-Scott/Notes-up#187]
When the pdf export dialog is cancel for not export the note, a pdf file is created with the current note and is name is "sortie.pdf' in french (i suppose "out.pdf" in english).

**Comment by dabou** [comment]
![bug-cancel-export-pdf](https://user-images.githubusercontent.com/1374934/30820021-f9dec236-a220-11e7-8b31-161f6c50b0ce.gif)

**Comment by Philip-Scott** [comment]
Btw, next time you do a pull request, if you type `fixes #bug` exactly like that, the bug you mentioned will get closed automatically :) Thank you for your contribution!
