### ISSUE TITLE
This is a feature request.

### ISSUE THREAD

**Issue by JamesTiberiusKirk** [Philip-Scott/Notes-up#188]
Maybe add some keyboard shortcuts.  
For example: f5 for switching between the view and edit mode.

**Comment by Philip-Scott** [comment]
You can switch between modes using `Ctrl+M`. If you hover over the buttons, you can also see which shortcut it uses :)

**Comment by JamesTiberiusKirk** [comment]
Ah, thanks, donno how I didn't notice that before.
Also, how can I see the version number?
I'm compiling from source and I just want to see if it was upgraded properly.

**Comment by Philip-Scott** [comment]
They don't really exist in code anymore. The "version number" is generated with AppStream when it lands on the PPA for the elementary AppCenter

You could add a `stderr.printf ("TESTING\n");` to the code, and if you see it it means that it's properly installed :D
