### ISSUE TITLE
Cant compile due to missing libmarkdown library

### ISSUE THREAD

**Issue by Streppel** [Philip-Scott/Notes-up#192]
Just pulled the project and installed its dependencies. After running _cmake -DCMAKE_INSTALL_PREFIX=/usr ../_, I run _sudo make install_, however I get the following error message:

**make[2]: *** No rule to make target 'libmarkdown.a', needed by 'notes-up'.  Stop.
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/notes-up.dir/all' failed
make[1]: *** [CMakeFiles/notes-up.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2**

I don't understand this issue since discount is bundled within the project. Any ideas on how to proceed?

Full output below:

$ sudo make install
Scanning dependencies of target discount
[  2%] Completed 'discount'
[ 16%] Built target discount
[ 18%] Generating src/Main.c, src/Application.c, src/Widgets/Editor.c, src/Widgets/HelpBox.c, src/Widgets/Headerbar.c, src/Widgets/ViewEditStack.c, src/Widgets/ToolbarButton.c, src/Widgets/BookmarkButton.c, src/Widgets/PageItem.c, src/Widgets/PagesList.c, src/Widgets/Viewer.c, src/Widgets/Window.c, src/Widgets/Sidebar/Sidebar.c, src/Widgets/Sidebar/SidebarItem.c, src/Widgets/Sidebar/NotebookItem.c, src/Widgets/Sidebar/BookmarkItem.c, src/Widgets/Sidebar/TrashItem.c, src/Widgets/Dialogs/NewNotebookDialog.c, src/Widgets/Dialogs/PreferencesDialog.c, src/Styles/air.c, src/Styles/elementary.c, src/Styles/modest.c, src/Services/Bookmark.c, src/Services/FileManager.c, src/Services/Notebook.c, src/Services/Image.c, src/Services/Page.c, src/Services/Settings.c, src/Services/Trash.c, src/Services/DatabaseTable.c, src/Plugins/Manager.c, src/Plugins/Plugin.c, src/Plugins/Break.c, src/Plugins/Color.c, src/Plugins/Youtube.c, src/Plugins/Image.c, src/Plugins/Highlight.c, src/config.c
gtksourceview-3.0.vapi:79.4-79.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:133.4-133.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:136.4-136.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:138.4-138.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:147.4-147.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:285.4-285.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:288.4-288.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:294.4-294.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:300.4-300.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:303.4-303.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:369.4-369.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:374.4-374.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:379.4-379.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:467.4-467.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:476.4-476.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:483.4-483.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
gtksourceview-3.0.vapi:628.4-628.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:247.4-247.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:249.4-249.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:252.4-252.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:254.4-254.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:257.4-257.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:259.4-259.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:262.4-262.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:264.4-264.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:52.4-52.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:55.4-55.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:64.4-64.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:67.4-67.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:78.4-78.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:81.4-81.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:88.4-88.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:91.4-91.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:95.4-95.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:237.4-237.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:275.4-275.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:283.4-283.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:351.4-351.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:439.4-439.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:504.4-504.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:529.4-529.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:627.3-627.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:644.4-644.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:646.4-646.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:649.4-649.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:659.4-659.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:663.4-663.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:665.4-665.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:669.4-669.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:677.4-677.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:680.4-680.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:686.4-686.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:689.4-689.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:720.4-720.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:763.4-763.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:776.4-776.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:786.4-786.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:794.4-794.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:797.4-797.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:803.4-803.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:806.4-806.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:945.3-945.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:952.4-952.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:954.4-954.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1052.3-1052.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1321.3-1321.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1522.3-1522.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1531.3-1531.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1534.3-1534.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1541.3-1541.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1544.3-1544.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1655.3-1655.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1658.3-1658.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1661.3-1661.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1664.3-1664.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1667.3-1667.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1670.3-1670.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1673.3-1673.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1676.3-1676.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1679.3-1679.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1682.3-1682.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1711.3-1711.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1714.3-1714.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1717.3-1717.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1728.3-1728.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1731.3-1731.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1734.3-1734.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1737.3-1737.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1740.3-1740.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1743.3-1743.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1746.3-1746.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1749.3-1749.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1752.3-1752.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1755.3-1755.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1758.3-1758.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1761.3-1761.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1764.3-1764.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1767.3-1767.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1770.3-1770.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1781.3-1781.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1785.3-1785.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1788.3-1788.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1791.3-1791.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1794.3-1794.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1797.3-1797.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1800.3-1800.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1803.3-1803.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1806.3-1806.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1809.3-1809.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1812.3-1812.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libsoup-2.4.vapi:1816.3-1816.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
/home/kapyvara/src/Notes-up/src/Services/Image.vala:84.25-84.70: warning: unhandled error `GLib.Error'
        var file_info = file.query_info ("*", FileQueryInfoFlags.NONE);
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/kapyvara/src/Notes-up/src/Services/Image.vala:115.13-115.82: warning: unhandled error `GLib.FileError'
            GLib.FileUtils.get_contents (file.get_path (), out data_raw, out size);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/kapyvara/src/Notes-up/src/Widgets/Viewer.vala:99.13-99.24: warning: `null' incompatible with return type `Gtk.Widget`
            return null;
            ^^^^^^^^^^^^
/home/kapyvara/src/Notes-up/src/Widgets/Editor.vala:57.41-57.61: warning: Access to static member `ENotes.Services.Settings.get_instance' with an instance reference
                    var last_language = settings.get_instance ().spellcheck_language;
                                        ^^^^^^^^^^^^^^^^^^^^^
/home/kapyvara/src/Notes-up/src/Widgets/Editor.vala:131.22-131.42: warning: Access to static member `ENotes.Services.Settings.get_instance' with an instance reference
        spellcheck = settings.get_instance ().spellcheck;
                     ^^^^^^^^^^^^^^^^^^^^^
/home/kapyvara/src/Notes-up/src/Widgets/Editor.vala:140.25-140.45: warning: Access to static member `ENotes.Services.Settings.get_instance' with an instance reference
                        settings.get_instance ().spellcheck_language = selected.label;
                        ^^^^^^^^^^^^^^^^^^^^^
/home/kapyvara/src/Notes-up/src/Widgets/Editor.vala:300.9-300.31: warning: Gtk.Widget.override_font has been deprecated since 3.16
/home/kapyvara/src/Notes-up/src/Widgets/Headerbar.vala:131.25-131.57: warning: unhandled error `GLib.Error'
                        contract.execute_with_file (file);
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/kapyvara/src/Notes-up/src/Widgets/Headerbar.vala:120.25-120.98: warning: unhandled error `GLib.Error'
        var contracts = Granite.Services.ContractorProxy.get_contracts_by_mime ("application/pdf");
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/kapyvara/src/Notes-up/src/Widgets/PagesList.vala:299.5-299.29: warning: method `ENotes.PagesList.translations' never used
    private void translations () {
    ^^^^^^^^^^^^^^^^^^^^^^^^^
/home/kapyvara/src/Notes-up/src/Services/DatabaseTable.vala:44.42-44.63: warning: use of possibly unassigned parameter `app_version'
    public VerifyResult verify_database (out string app_version, out int schema_version) {
                                         ^^^^^^^^^^^^^^^^^^^^^^
/home/kapyvara/src/Notes-up/src/Services/DatabaseTable.vala:44.66-44.87: warning: use of possibly unassigned parameter `schema_version'
    public VerifyResult verify_database (out string app_version, out int schema_version) {
                                                                 ^^^^^^^^^^^^^^^^^^^^^^
/home/kapyvara/src/Notes-up/src/Services/DatabaseTable.vala:116.20-116.65: warning: local variable `cmdline' declared but never used
            string cmdline = "cp " + backup_path + " " + filename;
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation succeeded - 124 warning(s)
Scanning dependencies of target notes-up
[ 20%] Building C object CMakeFiles/notes-up.dir/src/Main.c.o
[ 22%] Building C object CMakeFiles/notes-up.dir/src/Application.c.o
[ 25%] Building C object CMakeFiles/notes-up.dir/src/Widgets/Editor.c.o
[ 27%] Building C object CMakeFiles/notes-up.dir/src/Widgets/HelpBox.c.o
[ 29%] Building C object CMakeFiles/notes-up.dir/src/Widgets/Headerbar.c.o
[ 31%] Building C object CMakeFiles/notes-up.dir/src/Widgets/ViewEditStack.c.o
[ 33%] Building C object CMakeFiles/notes-up.dir/src/Widgets/ToolbarButton.c.o
[ 35%] Building C object CMakeFiles/notes-up.dir/src/Widgets/BookmarkButton.c.o
[ 37%] Building C object CMakeFiles/notes-up.dir/src/Widgets/PageItem.c.o
[ 39%] Building C object CMakeFiles/notes-up.dir/src/Widgets/PagesList.c.o
[ 41%] Building C object CMakeFiles/notes-up.dir/src/Widgets/Viewer.c.o
[ 43%] Building C object CMakeFiles/notes-up.dir/src/Widgets/Window.c.o
[ 45%] Building C object CMakeFiles/notes-up.dir/src/Widgets/Sidebar/Sidebar.c.o
[ 47%] Building C object CMakeFiles/notes-up.dir/src/Widgets/Sidebar/SidebarItem.c.o
[ 50%] Building C object CMakeFiles/notes-up.dir/src/Widgets/Sidebar/NotebookItem.c.o
[ 52%] Building C object CMakeFiles/notes-up.dir/src/Widgets/Sidebar/BookmarkItem.c.o
[ 54%] Building C object CMakeFiles/notes-up.dir/src/Widgets/Sidebar/TrashItem.c.o
[ 56%] Building C object CMakeFiles/notes-up.dir/src/Widgets/Dialogs/NewNotebookDialog.c.o
[ 58%] Building C object CMakeFiles/notes-up.dir/src/Widgets/Dialogs/PreferencesDialog.c.o
[ 60%] Building C object CMakeFiles/notes-up.dir/src/Styles/air.c.o
[ 62%] Building C object CMakeFiles/notes-up.dir/src/Styles/elementary.c.o
[ 64%] Building C object CMakeFiles/notes-up.dir/src/Styles/modest.c.o
[ 66%] Building C object CMakeFiles/notes-up.dir/src/Services/Bookmark.c.o
[ 68%] Building C object CMakeFiles/notes-up.dir/src/Services/FileManager.c.o
[ 70%] Building C object CMakeFiles/notes-up.dir/src/Services/Notebook.c.o
[ 72%] Building C object CMakeFiles/notes-up.dir/src/Services/Image.c.o
[ 75%] Building C object CMakeFiles/notes-up.dir/src/Services/Page.c.o
[ 77%] Building C object CMakeFiles/notes-up.dir/src/Services/Settings.c.o
[ 79%] Building C object CMakeFiles/notes-up.dir/src/Services/Trash.c.o
[ 81%] Building C object CMakeFiles/notes-up.dir/src/Services/DatabaseTable.c.o
[ 83%] Building C object CMakeFiles/notes-up.dir/src/Plugins/Manager.c.o
[ 85%] Building C object CMakeFiles/notes-up.dir/src/Plugins/Plugin.c.o
[ 87%] Building C object CMakeFiles/notes-up.dir/src/Plugins/Break.c.o
[ 89%] Building C object CMakeFiles/notes-up.dir/src/Plugins/Color.c.o
[ 91%] Building C object CMakeFiles/notes-up.dir/src/Plugins/Youtube.c.o
[ 93%] Building C object CMakeFiles/notes-up.dir/src/Plugins/Image.c.o
[ 95%] Building C object CMakeFiles/notes-up.dir/src/Plugins/Highlight.c.o
[ 97%] Building C object CMakeFiles/notes-up.dir/src/config.c.o
make[2]: *** No rule to make target 'libmarkdown.a', needed by 'notes-up'.  Stop.
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/notes-up.dir/all' failed
make[1]: *** [CMakeFiles/notes-up.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Philip-Scott** [comment]
I'm guessing you're not using elementary OS, correct? Can you try running the instructions on https://github.com/Philip-Scott/Notes-up/wiki/Build-and-Install-on-Ubuntu-16.04,-16.10,-17.04,-17.10


Or maybe try to install the Flatpak, Notes-Up is currently available on https://flathub.org/apps.html

**Comment by Streppel** [comment]
I'm actually running Elementary Loki, which is weird. Maybe I should give it a try on the ubuntu instructions anyway?

**Comment by Streppel** [comment]
Ok, so I managed it to work by simply deleting everything and downloading it back again lol, so I'll close this issue. Thanks for the quick reply, Philip, I appreciate it

**Comment by Philip-Scott** [comment]
Glad that fix it! :joy: Any time!
