### ISSUE TITLE
Unable to install on Ubuntu 16.04

### ISSUE THREAD

**Issue by banerjeesamrat** [Philip-Scott/Notes-up#193]
sudo apt-get install com.github.philip-scott.notes-up
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 com.github.philip-scott.notes-up : Depends: libgranite3 (>= 0.2.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

I was looking for solutions in the issues section, found this -

sudo apt-get install libgranite-dev libgee-0.8-dev libgtksourceview-3.0-dev libwebkit2gtk-4.0-dev libsqlite3-dev

Still getting same error.

**Comment by Streppel** [comment]
This is not exactly a problem with Notes-up, it's about Ubuntu not having libgranite available at the default repositories. I believe you'll need to add one of these PPA locations **ppa:elementary-os/stable** or **ppa:elementary-os/daily** before trying to install libgranite. Give it a try and see if it works.

**Comment by SuperThunder** [comment]
I run ElementaryOS on Ubuntu and these are the instructions I followed:
- sudo add-apt-repository ppa:elementary-os/daily
- sudo add-apt-repository ppa:elementary-os/os-patches
- sudo add-apt-repository ppa:philip.scott/notes-up
- sudo apt update
- sudo apt install com.github.philip-scott.notes-up

This does end up replacing a few Ubuntu packages (GRUB, the PDF viewer, the archive manager) with the Elementary versions.

**Comment by Philip-Scott** [comment]
You shouldn't need the `elementary-os/os-patches` PPA. the latest granite is in the daily ppa

**Comment by banerjeesamrat** [comment]
But when I am running this **sudo add-apt-repository ppa:elementary-os/daily** it shows this following message:
![image](https://user-images.githubusercontent.com/31121849/31481465-02282794-af13-11e7-95e0-75c3f2e4ae7c.png)

I am apprehensive about running this after the above warning. 
I have a lot of work saved on this system so will it be safe to run this command?

**Comment by Philip-Scott** [comment]
@banerjeesamrat Just to make sure nothing gets overtitten: 

Run upgrades first 
Then add the PPA, and try to run upgrades again
There shouldn't be any upgrades, or maybe only one for granite 

Can you tell me if you were successful in installing after this? Thanks!
