### ISSUE TITLE
Dewrapping deletes letters

### ISSUE THREAD

**Issue by snowparrot** [Philip-Scott/Notes-up#204]
@Streppel 
In the master branch if you dewrap (like bold) words some letters are deleted.

It is easier to see the bug if you use a longer text and you bold and debold inside words.

**Comment by Philip-Scott** [comment]
Can you give the example of some words that get messed up?

**Comment by Streppel** [comment]
@snowparrot also, is it selected or unselected text? I didn't see any similar case on my testings

**Comment by snowparrot** [comment]
Now I can reproduce the bug. I will open a new issue.
