### ISSUE TITLE
Dewrapping doesnt work for special characters

### ISSUE THREAD

**Issue by snowparrot** [Philip-Scott/Notes-up#205]
If you dewrap following text bigger parts are deleted. It looks very random. E.g. If you bold "des ÖRF war", you delete the last letter r.

Der Sinn des ÖRF war " „im Interesse von Informationsfreiheit und Demokratie, ein vielfältiges, umfassendes und ausgewogenes mediales Angebot zu sichern.“ (Wikipedia Grundversorgung)

**Comment by Philip-Scott** [comment]
Ohh i see, you're right! It has to do with the way special characters are encoded. In unicode, i think special characters might be considered two chars instead of one when it turns into a string, but not when viewed.

Nice catch @snowparrot :+1: 

Do you or @Streppel  wanna take care of it? :)

**Comment by Philip-Scott** [comment]
This is most likely where the problem is occurring: https://github.com/Philip-Scott/Notes-up/blob/master/src/Services/WordWrapper.vala#L53

Make sure to take into account the changes #202 may bring to avoid conflicts :)

**Comment by Streppel** [comment]
@Philip-Scott @snowparrot :+1: 
I can take a look into it later on when I get off work
