### ISSUE TITLE
TOC

### ISSUE THREAD

**Issue by fbruetting** [Philip-Scott/Notes-up#214]
Would be cool if you could also have the TOC displayed, like in Abricotine (maybe on the right side?).

![bildschirmfoto von 2017-11-11 03-40-36](https://user-images.githubusercontent.com/10520767/32685458-21ad8780-c692-11e7-8378-f1c1b5832bb1.png)

**Comment by Philip-Scott** [comment]
I'm going to close it since i don't think this is within the scope of the project
