### ISSUE TITLE
Showing the version number

### ISSUE THREAD

**Issue by fbruetting** [Philip-Scott/Notes-up#215]
Neither `notes-up --version` works, nor is the version number displayed somewhere in the GUI… ;P

**Comment by Philip-Scott** [comment]
About dialogs are deprecated in favor of AppData.

https://medium.com/elementaryos/peace-out-about-dialogs-8efa956c0562.

**Comment by fbruetting** [comment]
No “About dialog” – I’m talking about omnipresent and quasi-standard CLI query you’ll find in pretty ALL applications. How could you find out the version number, if there are GUI problems and the application doesn’t open up?
