### ISSUE TITLE
[Linux] Settings need double-click for closing

### ISSUE THREAD

**Issue by fbruetting** [Philip-Scott/Notes-up#216]
If I click on the close button of the settings for the first time, nothing happens. I always have to click a second time, then the window closes.

**Comment by fbruetting** [comment]
What means “Bite-size” actually?

**Comment by Philip-Scott** [comment]
It means that it's a good first bug for someone who wants to get into coding/contribute :)

In this case, i think that we should just remove the close button since:

- There's already a cancel button
- Close isn't specific whether it saves or not

**Comment by fbruetting** [comment]
I think it’s useful if you don’t want to save changes…?

**Comment by Philip-Scott** [comment]
I'm tripping, the preferences dialog doesn't have a cancel button ;P 

But nah, changes are applied "live". Close should just close

**Comment by fbruetting** [comment]
Then I’d suggest deleting the button and use the close button of the window, because the button then is superfluous. ^^

**Comment by Philip-Scott** [comment]
I think i'll use instead the close button on the dialog to keep it consistent with the other dialogs in elementary OS

![image](https://user-images.githubusercontent.com/10786508/32685660-6dc12a96-c65b-11e7-8616-ae6dd56c9d96.png)

**Comment by fbruetting** [comment]
Ok, no idea of Elementary. But since Elementary is only a niche and almost everybody else uses Gnome, a distinction of cases would be nice, because in Gnome, the cross in the top bar is used throughout the system.

**Comment by Philip-Scott** [comment]
It's an app built specifically for elementary OS though :) I'm not going to add more code to change the behavior for every other distro (already added a way to disable some elementary-only features)

**Comment by fbruetting** [comment]
k
