### ISSUE TITLE
No “New page” by default

### ISSUE THREAD

**Issue by fbruetting** [Philip-Scott/Notes-up#218]
I think, the user should always have to create the first page. Otherwise projects holding just subprojects also contain a first page (which cannot be deleted right now).

**Comment by Philip-Scott** [comment]
Expected result: 

Only create a new page by default on empty "folders", check that it doesn't have a child folder as well

**Comment by fbruetting** [comment]
Then I create a project, and before I can create my subprojects, a new file will be created, which I (in this case) don’t need. So your expected scenario never happens, because newly created projects don’t have children. ;)

**Comment by Philip-Scott** [comment]
Yeah, but you can just delete it :) And once you delete it a new file won't be created anymore

But this way, as a user you can make a new subfolder and a new file will be ready for you to write :)

**Comment by fbruetting** [comment]
Ok, then you just have to fix the re-creation of the deleted “new page” at every program start. :)

**Comment by Philip-Scott** [comment]
Ok, i've made it so that the empty page is only created when the notebook is created. That way when you make a notebook you can go and type right away without having to click again for a new page.

Fixed in 05244d4
