### ISSUE TITLE
Youtube link not working

### ISSUE THREAD

**Issue by ammarriyaz** [Philip-Scott/Notes-up#219]
![screenshot from 2017-11-12 23-36-30](https://user-images.githubusercontent.com/33604484/32701828-902022e2-c802-11e7-9452-aa708360a807.png)

I am using the following method:

<youtube [https://www.youtube.com/watch?v=CB4YTTVtveg]>

The video is being shown in normal way in the viewer but not responding on being played

![screenshot from 2017-11-12 23-39-24](https://user-images.githubusercontent.com/33604484/32701851-cd08e158-c802-11e7-8a6a-17bbcadb6e45.png)

Waiting for your valuable advice
Thanks in advance

**Comment by banerjeesamrat** [comment]
@ammarriyaz 

Your method of insertion of link:

<youtube [https://www.youtube.com/watch?v=CB4YTTVtveg]>

It needs a minor change. Remove the square brackets. And it works

Refer @Philip-Scott answer here:

https://github.com/Philip-Scott/Notes-up/issues/164

**Comment by ammarriyaz** [comment]
Thanks alot man!
