### ISSUE TITLE
Notes Title not processing Mark Down in the First Line of Notes.

### ISSUE THREAD

**Issue by maheswaranapk** [Philip-Scott/Notes-up#22]
First Line of the Notes is taken as Notes Title.
But If I add any markdown to first line to make it bolder or something, Note Title was taken with Mark Down.

![rsz_screenshot_from_2016-03-29_120845](https://cloud.githubusercontent.com/assets/5757251/14099986/a0daa0c8-f5a7-11e5-8f54-b8c6dd3edca2.png)

**Comment by voline** [comment]
T'is a duplicate #9 
Its already in queue for the next release, v.1.2

**Comment by Philip-Scott** [comment]
Yeah, it's a duplicate :) I was planning on doing it for this release, but the current method is too slow...

But for now @maheswaranapk, if you use #'s to set the header of the title, those won't show up in the Notes list :)

**Comment by Philip-Scott** [comment]
Since it's a duplicate, i'm going to close it to clean up the issues list
