### ISSUE TITLE
Enumeration icon should be top-aligned

### ISSUE THREAD

**Issue by fbruetting** [Philip-Scott/Notes-up#221]
Like you see in my screen shot below, the enumeration point is down at the bottom – it would be nice, if this can be corrected to be placed at the top! :)

![bildschirmfoto von 2017-11-22 17-31-27](https://user-images.githubusercontent.com/10520767/33138610-374ce276-cfab-11e7-94d6-4781eddc0bc4.png)

**Comment by Philip-Scott** [comment]
Can't be fixed with just CSS, sorry. But it does not occur when using normal text instead of a code block
