### ISSUE TITLE
Recommend having a look at Mermaid

### ISSUE THREAD

**Issue by mtompkins** [Philip-Scott/Notes-up#224]
Very nice app. You may want to incorporate this:
https://mermaidjs.github.io/

Good luck!

**Comment by Philip-Scott** [comment]
I feel that the use cases for having this in Notes-Up is very small, but it might be a great opportunity for someone to make this as an external application :) Plus, you can always import images.

Closing and marking as out of scope

**Comment by aljelly** [comment]
Actually, you can use it already. Example (remove the space in the code tag):

```markdown
# Graph test
My graph:

```mermaid
    graph LR
        A[this works]-->B[hello]
`` `
  ^ remove space



<script src=https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js></script>
<style>.mermaid {background-color:inherit;border:none;border-radius:0;padding:inherit;margin:inherit;font-family:"Open Sans";}</style>
```

Results in:
![image](https://user-images.githubusercontent.com/10395308/37542304-a267c28e-2955-11e8-81b1-d8fc25272c1f.png)

You can also apply it to every page if you want, though it's a bit hacky.

Go to Preferences > Viewer and add this to the style modifications:
```html
.mermaid {
	background-color: inherit;
	border: none;
	border-radius: 0;
	padding: inherit;
	margin: inherit;
	font-family: "Open Sans";
}
</style>
<script src=https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js></script>
```

Now you can remove the `<script>` and `<style>` code at the bottom of the example above and mermaid will work on all pages. It looks tidier when editing the note too.

**Comment by fbruetting** [comment]
Doesn’t work for me. Could this be due to Flatpak portal blocking internet access?

**Comment by aljelly** [comment]
I got it working with Flatpak. Flatpak blocks internet access by default, so the easy way to fix it is to add `--share=network` to the exec arguments, like `flatpak run --share=network com.github.philip_scott.notes-up` (I tested it and this works).
