### ISSUE TITLE
Unable to locate package 'com.philip-scott...'

### ISSUE THREAD

**Issue by h-alex** [Philip-Scott/Notes-up#228]
I'm trying to install the Notes-up via ppa but I fail at the last step.
Trying to do `sudo apt-get install com.github.philip-scott.notes-up` 
will get me the error

`E: Unable to locate package com.github.philip-scott.notes-up`
`E: Couldn't find any package by regex 'com.github.philip-scott.notes-up'`

**Comment by Philip-Scott** [comment]
What distro and version are you using? You might have to compile manually, or give me a few days to make a new build for it :)
