### ISSUE TITLE
Cannot launch Notes-Up (manually compiled)

### ISSUE THREAD

**Issue by MichaelAquilina** [Philip-Scott/Notes-up#236]
I followed the instructions on the README but when launching I get the following error:

```
./com.github.philip-scott.notes-up 
[INFO 20:33:38.380375] Application.vala:154: Notes-Up version: 1.3
[INFO 20:33:38.380418] Application.vala:156: Kernel version: 4.14.6-1-default
[FATAL 20:33:38.503879] file /home/michael/Development/Notes-Up/src/Widgets/Headerbar.vala: line 120: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.elementary.Contractor was not provided by any .service files (g-dbus-error-quark, 2)
[FATAL 20:33:38.546818] [Gtk] gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed
[FATAL 20:33:38.546902] [Gtk] gtk_widget_freeze_child_notify: assertion 'GTK_IS_WIDGET (widget)' failed
```

I am running this on OpenSUSE tumbleweed. I tried installing from the link provided on the README, but it seems like the Notes-Up package isnt available anymore?

**Comment by Philip-Scott** [comment]
Run cmake again with the arg `-Dnoele=1` to disable the elementary OS only functionality :) 

https://github.com/Philip-Scott/Notes-up/wiki/Build-and-Install-on-Ubuntu-16.04,-16.10,-17.04,-17.10

**Comment by Philip-Scott** [comment]
@Mailaender Can you update the OpenSUSE recipe? The executable was changed from `notes-up` to `com.github.philip-scott.notes-up` :) 

Thanks!
