### ISSUE TITLE
don't override the system-provided CFLAGS

### ISSUE THREAD

**Issue by decathorpe** [Philip-Scott/Notes-up#238]
At <https://github.com/Philip-Scott/Notes-up/blob/master/CMakeLists.txt#L80>, you are overriding all system-provided CFLAGS with "-ggdb". This breaks builds in some environments and builds the program with "insecure" build flags (no PIE, etc.).
Please drop this line entirely, or replace it with `set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -ggdb")` if the "-ggdb" is really necessary.

**Comment by Philip-Scott** [comment]
Fixed in b70cc12 :)
