### ISSUE TITLE
Cannot create Javascript syntax highlighting

### ISSUE THREAD

**Issue by yerbestpal** [Philip-Scott/Notes-up#243]
Hey there,

I realise I have posted about similar issues in the past but I cannot find a solution. I'm learning Javascript right now and I cannot create the correct syntax highlighting for my notes. Any ideas?
![1](https://user-images.githubusercontent.com/15250241/35187223-53549a72-fe18-11e7-80ed-c3d2300619be.png)
![2](https://user-images.githubusercontent.com/15250241/35187224-53878306-fe18-11e7-955b-913d90e48d8d.png)

**Comment by yerbestpal** [comment]
Creating a brand new note, with the same parameters, i.e. `<highlight>` and `javascript` appended to the beginning of my code block, works perfectly. 

![3](https://user-images.githubusercontent.com/15250241/35187349-75db6d08-fe1a-11e7-9349-4c78b5af7a6b.png)

**Comment by Philip-Scott** [comment]
It's a webkit problem as far as I can tell. It usually happens when you use non-ASCII characters. Try deleting part of the text above to see which char is the culprit
