### ISSUE TITLE
Unconsistent markup in edit mode

### ISSUE THREAD

**Issue by fbruetting** [Philip-Scott/Notes-up#245]
The indentation layers behave different, like you see in my screen shot.

• It’s actually quite nice, that the third level is colored blue, which leads to a better distinction when searching through a longer page.
• But things like slanting and fat-red just works at the first two levels.

![bildschirmfoto von 2018-01-24 12-44-00](https://user-images.githubusercontent.com/10520767/35330773-f18ed0ba-0104-11e8-98dc-67fbbe425395.png)

**Comment by Philip-Scott** [comment]
Marking as "Out of Scope" since this is an issue with the Gtk SourceView theme, and not something from Notes-Up :)
