### ISSUE TITLE
Spaces destroy list rendering

### ISSUE THREAD

**Issue by fbruetting** [Philip-Scott/Notes-up#246]
Would be needed for alignment of notes in the Editor.

This:
```
- One space between dash and text
-  Two spaces between dash and text
-   Three spaces between dash and text
-    Four spaces between dash and text
-Zero spaces between dash and text
```
leads to this:
![bildschirmfoto von 2018-01-24 12-56-26](https://user-images.githubusercontent.com/10520767/35330998-0682aee6-0106-11e8-81d6-85eb5f37446b.png)

And this:
```
- 123 Blubb
-       Blubb (7 spaces)
- 123 Blubb
```
leads to this:
![bildschirmfoto von 2018-01-24 12-59-02](https://user-images.githubusercontent.com/10520767/35331069-6127c23c-0106-11e8-9ba3-ae19aeb35461.png)

**Comment by Philip-Scott** [comment]
Markdown and HTML always destroy trailing whitespace. It's just the way the standard is. If you want to indent it, indent with the - as well
