### ISSUE TITLE
could you make a flatpak for Notes-up?

### ISSUE THREAD

**Issue by altntowin** [Philip-Scott/Notes-up#247]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for Notes-up?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by Philip-Scott** [comment]
A flatpak is already available over at Flathub :) 

But other than that, same comment as applies: https://github.com/Philip-Scott/wallpaperize/issues/16#issuecomment-360959050
