### ISSUE TITLE
New Notebook option not immediately obvious

### ISSUE THREAD

**Issue by dar5hak** [Philip-Scott/Notes-up#256]
This might be very subjective, but as a user, it took me a while to figure out how to create a new notebook. I'm not sure if the settings menu is the best place for the option.

It would probably be more visible either in the header bar, or at the bottom of the notebook list, so that it aligns with the New Page option.

If you agree, I can make a PR. Else, feel free to close; it might be just me.

**Comment by Philip-Scott** [comment]
Mmmm i'm not sure that it would make sense in the bottom on the notebook list, since none of the other elementary apps have that style :thinking: 

How about making the word "Notebooks" on the notebook list right-clickable and adding the option to make a new notebook from there as well? :)

**Comment by dar5hak** [comment]
Oh yes! That's a great idea too. Let's go with that then? I'll see if I can hack it sometime this week.

**Comment by dar5hak** [comment]
Okay, I've run into #252 while compiling on Loki. :disappointed:

**Comment by Philip-Scott** [comment]
If you're good with git, try to revert to before this commit: https://github.com/Philip-Scott/Notes-up/commit/20077eecb5c499600bb39d05c64769b81d6d5a6e

I think `git checkout b70cc125cffddc4b5a761e88b855c16915666c0c` should do the trick

**Comment by dar5hak** [comment]
I'm not, but that worked. Thank you! :grinning:

**Comment by Philip-Scott** [comment]
If you want to learn more about git, this is a very good resource https://learngitbranching.js.org :) 

I would really recommend at least the first 2-3 lessons from there!

**Comment by dar5hak** [comment]
Whoa, this looks great! Thanks!

**Comment by dar5hak** [comment]
[This guy here](https://github.com/Philip-Scott/Notes-up/blob/46a0ec99e5ee4b0afc3f2d7be65a148588390aae/src/Widgets/Sidebar/Sidebar.vala#L25) needs to implement `get_context_menu ()`. And for that, it needs to be a subclass of `Granite.Widgets.SourceList.ExpandableItem`.

I'm thinking I'll put it in `Widgets/Sidebar/NotebookList.vala`. That sound okay to you?

**Comment by dar5hak** [comment]
(Bear with me, I'm a beginner to Vala.)

**Comment by Philip-Scott** [comment]
Yes, sounds good to me :) Just put the new class all the way at the bottom

**Comment by dar5hak** [comment]
Not sure what you meant by "all the way at the bottom", but I put it after all the `ExpandableItem`s.

**Comment by Philip-Scott** [comment]
Ahh i thought you would be adding the new class to the Sidebar class, but i misread it! I left a review on your PR btw!

**Comment by dar5hak** [comment]
Um, you might want to change the label here maybe?

**Comment by Philip-Scott** [comment]
Done :) thank you.i usually don't care about the labels once it's closed
