### ISSUE TITLE
Show note creation date in list

### ISSUE THREAD

**Issue by aljelly** [Philip-Scott/Notes-up#257]
Mockup:

![krita_edit_concept](https://user-images.githubusercontent.com/10395308/37468155-149512d2-285a-11e8-9947-bcb6aca74582.png)

(ignore the "Something" entry without a time and date)

The date would be the date and time the note was created.

**Comment by Philip-Scott** [comment]
That's actually a great idea! I'm actually already storing creation and modification dated in the database, I hope that I'm actually storing those values correctly :sweat_smile: 

I wonder if instead of creation date it should be modification date :thinking:

**Comment by aljelly** [comment]
You could show the modified date instead, I was going by what Standard Notes does. But I just discovered you can also show "date modified" in Standard Notes in place of "date added", depending on what you set sort by to. I presume it shows date added by default because it also sorts by that.

([Standard Notes is on the web](https://app.standardnotes.org/), close the Account dialog and try the sorting option to see what I mean.)

**Comment by Philip-Scott** [comment]
Closing this issue in favor for the new and cleaner page info widget
