### ISSUE TITLE
Misaligned line numbers

### ISSUE THREAD

**Issue by SolarLiner** [Philip-Scott/Notes-up#267]
Line numbers are misaligned with the content in the editor.
![image](https://user-images.githubusercontent.com/4302963/38329899-6c7e12c8-384f-11e8-90e7-8408da9fcf05.png)

**Comment by Philip-Scott** [comment]
Fixed in master, thank you for bringing it up! 

![image](https://user-images.githubusercontent.com/10786508/38367831-57549afc-38a9-11e8-86ce-b454146ceb81.png)
