### ISSUE TITLE
Not obvious where markdown files are stored

### ISSUE THREAD

**Issue by MichaelAquilina** [Philip-Scott/Notes-up#268]
I'm struggling to find where my markdown files are stored (so that they can be backed up for example).

I can find anything on the README and attempting to use grep to search my home directory proved fruitless.

It would be nice if this could be specified somewhere for those looking or it. Or better yet, make it a customisable field in preferences.

**Comment by MichaelAquilina** [comment]
I've just noticed from reading the source code that the Notebooks are stored in a database :/

Is there any way to get this to work so that it works with text files instead? Using plain text files is much more portable if you want it to work with other applications, command line tools etc. It also means its easier to inspect from the command line directly if you suddenly need to ssh into your machine and view the contents.

**Comment by PhilippeMorere** [comment]
I agree, I would love to get this feature. It would allow me to sync the .md files across several devices as well.

**Comment by MichaelAquilina** [comment]
Looking at the code, it wouldnt be extremely difficult to get this changed to use plain text files. The part that doesnt seem simple is coming up with a search mechanism to replace SQL text search. I wouldnt mind trying this out - but its quite a major change and I would like to hear what feedback @Philip-Scott has! :D

**Comment by Philip-Scott** [comment]
So a bit of history here! In it's super early days, Notes-Up used to use a folder to save all the notes, with each file being a note, etc. And honestly, it was a mess and changing to SQL was a huge step forward. There's just too much extra data to handle like pictures, extra styles, creation and modification date, colors, and also the favorites section. 

Instead of going back to using files, we should look at tacking importing and exporting files (#113) and maybe even being able to use notes-up to "Open With" markdown files

**Comment by SolarLiner** [comment]
As a mean of backup it'd be good to also be able to import/export the database if possible, or tell us where the database files are saved so that third-party backup tools can pick it up.

Having suffered from a recent disk data corruption, I want to be as safe as possible. ;)

**Comment by Philip-Scott** [comment]
Depending on how early on the life-cycle of the app you installed it, it should be on either ~/.local/ or `~/.local/share/notes-up` :) 

Ideally, normal users should have no need to ever access that file, but yeah i agree that maybe something should be done. Maybe i can have a button like on Spice-Up that opens the location of the database :thinking: 

![image](https://user-images.githubusercontent.com/10786508/38576667-677782d6-3cc4-11e8-87bc-cbe77c572a21.png)

**Comment by Philip-Scott** [comment]
Closing in favor of #148 :)
