### ISSUE TITLE
[Ubuntu 15.10] Cannot rename notebook

### ISSUE THREAD

**Issue by demonpig** [Philip-Scott/Notes-up#27]
OS: Ubuntu 15.10
Kernel: 4.2.0-35

Was not able to rename any notebooks by right clicking inside the notebook list.

**Comment by demonpig** [comment]
This also applies to Ubuntu 15.04

**Comment by Philip-Scott** [comment]
@demonpig did the right click menu not appear on the notebook list, or when the "Edit Dialog" box appears nothing changes?

**Comment by demonpig** [comment]
The right click menu does not appear at all on either Ubuntu 15.10 or 15.04.

**Comment by demonpig** [comment]
Later tonight, I will check to see what version is installed on Ubuntu 15.10. I believe the issue to be with Granite as well.

**Comment by Philip-Scott** [comment]
You know.... the more i think about it, the less i want to add support to other OSs....   http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html 

TBH, I think at most it would be better to just have an AppImage version, if that works and fixes everything then great! If not then it will not have support :P
