### ISSUE TITLE
Support icons for tagging

### ISSUE THREAD

**Issue by snowparrot** [Philip-Scott/Notes-up#272]
Colours arent very interesting for some tagging.
In addition Notes-Up should support tagging with a icon. It means instead of bubble with a colour you have an icon.

Good start point should emoticons in Juno.

**Comment by Philip-Scott** [comment]
Tags can now be used and emojis can be added to them:

![image](https://user-images.githubusercontent.com/10786508/54652133-580a1780-4a7b-11e9-8992-af1ce93fdcc2.png)

Coming soon in Notes-Up 2.0.0

**Comment by snowparrot** [comment]
Thanks!
