### ISSUE TITLE
In View mode, how do I make text take up more width?

### ISSUE THREAD

**Issue by proxycyber** [Philip-Scott/Notes-up#273]
I'd like the text to fill up more width of the page. How can I do this? I've tried a few CSS lines but I can't get it to how I like it. It seems pretty centered and narrow to me right now, I want it to take up a lot more of the white space in terms of width. Just a personal preference. Is there a way to do this?

**Comment by Philip-Scott** [comment]
try adding these lines on the app's or notebook's stylesheet:
```
body * {
    max-width: 100%;
}
``` 

This is the stylesheet in use so feel free to copy it and modify it to your liking https://github.com/Philip-Scott/Notes-up/blob/master/src/Styles/elementary.vala :)

**Comment by proxycyber** [comment]
You are FANTASTIC! Thanks for this. :+1:  :)
