### ISSUE TITLE
[Feature] Delete multiple pages from notebook

### ISSUE THREAD

**Issue by demonpig** [Philip-Scott/Notes-up#28]
Unless there is a specific way of deleting multiple pages from a notebook, I believe this would be a good feature to add. Right now the process is to select a page and click the delete button.

A possible solution would be to:
* Hold down Control to be able to select multiple pages
* Either click the delete button or hit the delete key on keyboard

**Comment by Philip-Scott** [comment]
If you clone master, you should be able to do this now :) 

It'll be pushed to the ppa once the milestone is done
