### ISSUE TITLE
Slow Transition When Switching Between Edit/View 

### ISSUE THREAD

**Issue by infosisio** [Philip-Scott/Notes-up#286]
This only happens after a change is made and with the sidebar always shown.

UPDATE: I just compiled and tested the latest version from source and I can't reproduce this there.

**Comment by Philip-Scott** [comment]
Yeah, a lot of optimizations have occurred since the last release :) Specially on the backend for markdown on Juno. 

I'll be closing this then, and any slowdowns on more "expensive" pages could be fixed with multi-threading, but it's something we should really avoid unless it's super necessary
