### ISSUE TITLE
Can I buy you a coffee in Bitcoin ? :)

### ISSUE THREAD

**Issue by infosisio** [Philip-Scott/Notes-up#290]
I really hope so !

If so, send me your address.

**Comment by Philip-Scott** [comment]
I don't use bitcoin, and sadly there's too many fees involved with it :) If you want to you can:
- buy the app on AppCenter (It will be released soon)
- use paypal
- Use that bitcoin to contribute to the Gtk or elementary OS devs instead :) They're also great and are what made all of this posible
