### ISSUE TITLE
Bug: exporting as PDF creates empty .pdf files

### ISSUE THREAD

**Issue by zervankoru** [Philip-Scott/Notes-up#293]

**Comment by yawner-dev** [comment]
Can confirm and it's a bit annoying. Since the preview works in app and I'm assuming it does a similar process to render the markdown it should only be a problem with the section that deals with the export.

**Comment by Philip-Scott** [comment]
@zervankoru  @yawner-dev  I'm guessing you guys don't use your computer in English. This is a problem with the translation that if you guys can help me out you would be able to fix it to everyone using your language :)

Check #1 for more info
