### ISSUE TITLE
Export to PDF returns a empty file

### ISSUE THREAD

**Issue by gughog** [Philip-Scott/Notes-up#296]
Hi there! I'm in loving with your app, It's very useful, but the function to export to pdf does't work when I try. It generates a empty file, and I can't upload the file here because that. You know what's happening or how I fix that ? 

Regards!

**Comment by Philip-Scott** [comment]
Hey! I'm guessing you don't use your computer in English. This is a problem with the translation that if you can help me out you would be able to fix it to everyone using your language :)

Check #1 for more info on how to solve it for you and everyone else!

**Comment by gughog** [comment]
And how can I translate It ? Sorry, I'm kind a newbie here in Github and I'm still learning the features like push and pull requests, and with Linux. Can I edit the file directly in my PC or can I just translate for you to include in the next updates ? I'm using PT-BR language settings.

**Comment by Philip-Scott** [comment]
@gughog It looks like it may be already fixed for just language, just maybe not yet available? Mind checking if the string in https://github.com/Philip-Scott/Notes-up/blob/master/po/pt_BR.po#L372 is correct?
