### ISSUE TITLE
The app doesn't show up in elementary OS Juno

### ISSUE THREAD

**Issue by andbuitra** [Philip-Scott/Notes-up#297]
Hello, Felipe.

I'm currently running Juno up-to-date but there's no app in the AppCenter even though you listed it on the releases page. Is this intentional? Thought I should let you know since I miss using your great app.

I did saw an AppCenter commit the other day so I assumed it was already published.

**Comment by Philip-Scott** [comment]
Hi! Thanks for writing an issue :)  I tried to make it so the new version on Notes-Up was released on both Loki and Juno, but sadly something with the build failed.... I think I will be dropping Loki support and just build from master from now on. 

Hopefully I'll get that sorted during the weekend :)

**Comment by Philip-Scott** [comment]
And it's out! :)
