### ISSUE TITLE
elementary viewer theme has ugly border when you change the color.

### ISSUE THREAD

**Issue by Nine-H** [Philip-Scott/Notes-up#300]
Working on a solarised version of the elementary theme, for low contrast and readability, for some reason the elementary theme is the only one that pulls in this really ugly white border.

![screenshot from 2018-11-09 17 34 50](https://user-images.githubusercontent.com/20123543/48247019-d1e32200-e445-11e8-852b-9d5a0892db58.png)

Obviously users can hack around it by changing the margins to padding in userCSS, but it'd be way cleaner to fix it in the core theme so simple userCSS like this works.

```
* {	
	background-color : #fdf6e3;
	color : #657b83;
}

h1, h2, h3 {
	color : #586e75;
}
```

**Comment by Philip-Scott** [comment]
Set the background-color on `html, body` as well :) No need to change paddings/margins within the CSS
