### ISSUE TITLE
Sharing Between Computers

### ISSUE THREAD

**Issue by gibranlp** [Philip-Scott/Notes-up#302]
Is there a way to, make possible to share the files, or to place the notes files on a different folder so they can be synchronized via ownclod, MEGA, or any other cloud service?

**Comment by Philip-Scott** [comment]
Database files are stored in `~/.local/share/notes-up/NotesUp.db` so you can do whatever you want with it :) There's also a gsettings key you can change under org/notes that let's you pick where it's stored

**Comment by Hedronmx** [comment]
Can you add gui to change the location of the database? That way we can set up syncing
