### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by alchehabi** [Philip-Scott/Notes-up#303]
**Description:**
The app crashes immediately and doesn't open.  I also recieve the following report after entering this command `com.github.philip-scott.note-up` in Terminal:

[INFO 09:47:36.562779] Application.vala:155: Notes-Up version: 1.3
[INFO 09:47:36.562814] Application.vala:157: Kernel version: 4.15.0-43-generic
**
ERROR:/build/com.github.philip-scott.notes-up-1.6.2/src/Services/DatabaseTable.vala:73:database_table_prepare_db: assertion failed: (res == Sqlite.OK)
Aborted

**Source of install:**
Appcenter on Juno (up to date).

**Comment by Philip-Scott** [comment]
Looks like it's failing on creation of the database. can you check if:

1. There's a file on `/home/{your-username}/.local/share/notes-up/NotesUp.db`?
2. Have you ever used Notes-Up before?

**Comment by alchehabi** [comment]
1. I just checked it out and it turns out that there is no note-up folder inside the share folder.
2. No, I didn't use it.

**Comment by Philip-Scott** [comment]
Looks like you may have used it before or something weird happened since it creates the folder the first time you run it. I'll patch it up soon so that it always creates the folder if it does not exist :) For now just make the folder manually and it will be working as normal

**Comment by alchehabi** [comment]
I think I did install it but never used it. I'll do that :)

**Comment by Philip-Scott** [comment]
Fixed in fa0cf30. Thank you for bringing this up :) 

Will be releasing a new version on AppCenter soon to fix this
