### ISSUE TITLE
Selected dictionary language get reverted

### ISSUE THREAD

**Issue by zeebok** [Philip-Scott/Notes-up#304]
**Expected Behavior**
When I have the Languages sub-menu open (reached by right-clicking while editing a note) and I click to close the entire context menu tree, the menu closes and no changes are made.

**Actual Behavior**
I have the Languages sub-menu open and I click outside of the context menu to close the tree; the menu closes and the dictionary language is set back to bg_BG. I suspect that it is that specific language only because it is the first in the list.

**Comment by Philip-Scott** [comment]
Fixed in f8c3855
