### ISSUE TITLE
Dconf file is too large (~1.1 MB) with notes-up installed.

### ISSUE THREAD

**Issue by Innocent-eyes** [Philip-Scott/Notes-up#305]
try to do
`bash -c 'gsettings list-recursively > ./dconf\ $(date +%Y-%m-%d).settings'`

Dconf file is too large (~1.1 MB) with notes-up installed.
Normal size is about ~150 kB.

`org.notes.notebook_data.notebook stylesheet-changes ''
org.notes.notebook_data.notebook stylesheet 'default'
org.notes.notebook_data.notebook stylesheet-changes ''
org.notes.notebook_data.notebook stylesheet 'default'
org.notes.notebook_data.notebook stylesheet-changes ''
org.notes.notebook_data.notebook stylesheet 'default'
org.notes.notebook_data.notebook stylesheet-changes ''
org.notes.notebook_data.notebook stylesheet 'default'
org.notes.notebook_data.notebook stylesheet-changes ''
org.notes.notebook_data.notebook stylesheet 'default'
org.notes.notebook_data.notebook stylesheet-changes ''
org.notes.notebook_data.notebook stylesheet 'default'
org.notes.notebook_data.notebook stylesheet-changes ''
org.notes.notebook_data.notebook stylesheet 'default'
org.notes.notebook_data.notebook stylesheet-changes ''
org.notes.notebook_data.notebook stylesheet 'default'
org.notes.notebook_data.notebook stylesheet-changes ''
`

**Comment by Philip-Scott** [comment]
Did you happen to add a large amount of lines to the custom CSS within the settings?  Notes-Up comes from when I started coding so I didn't really know about good practices, but I'll add on the next version a transition to move that out and into an actual file :)

**Comment by Philip-Scott** [comment]
Fixed in 404761c
