### ISSUE TITLE
Building on Fedora

### ISSUE THREAD

**Issue by HarlemSquirrel** [Philip-Scott/Notes-up#308]
I wanted to share how I built this on Fedora

```
git clone https://github.com/Philip-Scott/Notes-up
cd Notes-up
mkdir build && cd build
sudo dnf install granite-devel gtksourceview3-devel gtk+-devel webkit2gtk3-devel gtkspell3-devel libmarkdown-devel vala-devel
cmake -DCMAKE_INSTALL_PREFIX=/usr -Dnoele=1 ../
```

**Comment by Philip-Scott** [comment]
Glad to know that it's working in Fedora :) 

I'm closing this since it's not an issue, but the info is available here: 
https://github.com/Philip-Scott/Notes-up/wiki/Build-and-Install-on-Ubuntu-and-other-distros/
