### ISSUE TITLE
Exporting PDF Notebooks

### ISSUE THREAD

**Issue by bridgetsarah** [Philip-Scott/Notes-up#313]
Not too sure if I came across a bug the other day when I tried to export my note books but in the end had to copy and paste every page as every time I tried to export, it gave me a blank PDF.  At the time I was using Linux Mint (Cinnamon edition) so I am unsure whether its a compatibility issue as I understand this was developed for another os 

Still doesn't stop me from reinstalling it, but if you could just take a look into it, would be a great :)

**Comment by Philip-Scott** [comment]
I'm guessing you might be using the app in a different language? :) That's currently a limitation but you can help me fix it for everyone using your language by following the steps in #1 :)

**Comment by bridgetsarah** [comment]
Haha thanks for the invite! I'll see if I can look into it when I've got some time this week ;)
