### ISSUE TITLE
Interoperability with mobile clients (NextCloud, Drive, DropBox, ...)

### ISSUE THREAD

**Issue by kr428** [Philip-Scott/Notes-up#314]
Notes-Up is pretty awesome but for real-world use cases these days it doesn't get me very far without being able to somehow synchronize my notes with my mobile device (Android in my case) and read / edit them on there. Anything like this planned or possible?
Thanks,
Kristian

**Comment by Philip-Scott** [comment]
Closing this in favor of #330. I won't be adding support for mobile clients, but at least with this feature you would be able to open your notes from your phone within your network :)
