### ISSUE TITLE
Is a snap on the cards?

### ISSUE THREAD

**Issue by rolandixor** [Philip-Scott/Notes-up#317]
I'd like to install on Ubuntu, but I've had some issues with the elementary PPA in the past.
As for why use a snap over a flatpak? Not a hugely technical reason, but just I prefer having less things to remember (and snap install/run/etc/etc nameofapplication is easier than flatpak install/run/whatever this.that.the.next.the.third.flatpakref etc).

**Comment by Philip-Scott** [comment]
Sorry, but I won't be committing to offering a Snap anytime soon. If anyone is willing to put in the effort to package and maintain the snap, that's great! But for the meantime it is something that i can't commit to offer. Hope you understand
