### ISSUE TITLE
All writing is detected is incorrectly spelled.

### ISSUE THREAD

**Issue by yerbestpal** [Philip-Scott/Notes-up#318]
When spell-checking is enabled, almost all text is considered incorrectly spelled. In a paragraph or around 100 words, there are maybe 10+ words considered correctly spelled. Either there is an issue with the software, or I am more poor with spelling than I realised.

**Comment by Philip-Scott** [comment]
Did you set the spellchecker language by right clicking the word? :)

**Comment by yerbestpal** [comment]
I did not and that's solved my issue, apologies. I genuinely did not think of right-clicking the text area for some reason.
