### ISSUE TITLE
Unable to build Notes-Up on Loki

### ISSUE THREAD

**Issue by gdeflaux** [Philip-Scott/Notes-up#319]
Hi,

When I run the commands listed in the README to build Notes-Up I got some errors related to missing packages. I've `sudo apt install` all of them but none the less I still get the error for 2 missing packages.

```
-- Checking for modules 'granite>=5.2.0;gee-0.8;gtksourceview-3.0>=3.10;gthread-2.0;gtk+-3.0>=3.9.10;webkit2gtk-4.0;sqlite3>=3.5.9;gtkspell3-3.0;libmarkdown'
--   No package 'gtkspell3-3.0' found
--   No package 'libmarkdown' found
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:13 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/guillaume/Documents/code/Notes-up/build/CMakeFiles/CMakeOutput.log".
```

If I try `sudo apt install gtkspell3-3.0` I get the following output:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'gir1.2-gtkspell3-3.0' for regex 'gtkspell3-3.0'
Note, selecting 'libgtkspell3-3-0' for regex 'gtkspell3-3.0'
gir1.2-gtkspell3-3.0 is already the newest version (3.0.9-2).
libgtkspell3-3-0 is already the newest version (3.0.9-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Similar output for libmarkdown, hinting that the packages are indeed install on my system.

Any idea what I could try to solve this, or what else to check?

Thanks,

**Comment by Philip-Scott** [comment]
Hey! Sadly, I'm no longer giving support for elementary OS Loki (the Ubuntu version it is based on is even just about to stop getting security support, so I'd really recommend that you update to Juno if you can)

iirc, this was the last tag that was made using Loki. It's pretty outdated but you may be able to get it running:

https://github.com/Philip-Scott/Notes-up/releases/tag/1.5.2

**Comment by gdeflaux** [comment]
Hi,

Sorry I mistakenly mentioned Loki. I am indeed on Juno and I've updated the title.

Cheers,
