### ISSUE TITLE
When deleting a note, why must the app be restarted?

### ISSUE THREAD

**Issue by proxycyber** [Philip-Scott/Notes-up#320]
I do have confirmation that the note is deleted, but it feels like I'm back in the old days where software was limited and so restarting the app makes it work well again. I really love Notes-up, but small things like this can be annoying, particularly if I want that free space and for it not to show visibly in my list of notes, especially if it's been deleted. I don't mean any of this in a rude way, but we're in 2019... we should never need to restart an app for anything to work properly (unless it's a bug, then, of course, it'll get fixed).

**Comment by Philip-Scott** [comment]
They are deleted on restart by design, to allow the user to restore them and also so they're automatically deleted when you manually close the app, so keep the user never has to think about "emptying the trash"
