### ISSUE TITLE
Pick a location to store db file

### ISSUE THREAD

**Issue by Gotterbild** [Philip-Scott/Notes-up#322]
Hey, Philip @Philip-Scott I'm not sure if this is a duplicate. I've looked into related issues, but it looks my view is a bit wider and partially covers all involved issues.

First, thanks for a great app. Linux lacks apps with a solid UI and yours is a great exception. However, it lacks one functionality that stops me from using it: syncing.

I understand that the best way to perform sync is to have some account (maybe, GNOME account - the same way Apple Notes work). However, I understand all technical issues involved and don't request that.

But there is a way that is easier to implement and will work for my case (and I guess other people cases as well). 

I can see you mention `sqlite` in one of comments, so I guess you use sqlite as a database for notes. Why don't you add a function to have a custom location to save the database? This will solve:
1. Sync. I can just put Notes-Up db file into my cloud folder (Yandex Disk, NextCloud, Dropbox, Google Drive, etc), which will automatically sync db file to cloud storage.
2. Transferability. You can throw your notes DB to any device manually. 
3. #211 
4. #321  
5. Partially #198. Actually, #198 will work for my case as well.
6. Partially #113 
7. #314 Actually, my idea is kinda duplicate of that.
8. Besides of having multiple notebooks in app, there will be ability to have multiple DBs. For example, someone would want to have his personal db separate from a work db.

For people who want to keep their notes secret, there even can be an option to encrypt data. However, that is a priority at all (for me).

Tell me what you think. Thanks.

**Comment by proxycyber** [comment]
I definitely agree with this!

**Comment by Philip-Scott** [comment]
It may sound weird, but i don't really like the idea of user's having to manually "Import and export" the Notes-Up files. I am thinking about an alternative where the database is actually `notes.nbk` file inside the user's Documents folder, and that file can be opened by the user. This way, you could have multiple "Notebook" files in the same computer, and share/sync those as user's wish. Basically i'd like to have the OneNote "UX" 

There has to be some sort of "migration" strategy though, as well as UI for when the user first boots the app so they can select the file name and all

**Comment by Gotterbild** [comment]
Actually, that is exactly what I need.

I understand why you don't want to have `Open Notebook` functionality. But having a preferences option to select a folder to store your notebooks file will do the trick.
