### ISSUE TITLE
Why do we need to restart the app after deleting a note to see that it's been deleted?

### ISSUE THREAD

**Issue by proxycyber** [Philip-Scott/Notes-up#324]
I do have confirmation that the note is deleted, but it feels like I'm back in the old days where software was limited and so restarting the app makes it work well again. I really love Notes-up, but small things like this can be annoying, particularly if I want that free space and for it not to show visibly in my list of notes, especially if it's been deleted. I don't mean any of this in a rude way, but we're in 2019... we should never need to restart an app for anything to work properly (unless it's a bug, then, of course, it'll get fixed). When I'm in the zone and working, I'd rather not have to restart so as to lose the place and focus.

**Comment by Philip-Scott** [comment]
Closing this issue.... It's not really cool to spam an issue btw... #320  :P
