### ISSUE TITLE
Double click notes to edit

### ISSUE THREAD

**Issue by voline** [Philip-Scott/Notes-up#33]
Or introduce a keyboard shortcut to go straight to the edit pane, as an additional choice to the "view" and "edit" buttons on the header bar.

**Comment by Philip-Scott** [comment]
Ctrl + M, m as in "mode" 😉

I really need to make that more discoverable though.... Maybe I'll add the shortcut to the tooltip

**Comment by voline** [comment]
So sorry. You are doing a fine job!

**Comment by Philip-Scott** [comment]
Hey no! No sorry! You not knowing about it *IS* a bug in my book. ☺️ I do like the idea of the double click though, although I gotta think about things like "Should it also switch to view mode if you were in edit?"

Thank you for reporting it! It's great knowing at least someone else is also using it 😄

**Comment by Philip-Scott** [comment]
TODO: 

- [x] Double click notes to change modes
- [ ] Show shortcuts somewhere in the UI

**Comment by Philip-Scott** [comment]
Commit 3f3d8153e31c554e4d180104b4188d76619113ac shows the shortcuts besides the buttons :smiley:
