### ISSUE TITLE
Don't use hardcoded path to database in GSettings

### ISSUE THREAD

**Issue by worldofpeace** [Philip-Scott/Notes-up#332]
## Expected Behavior
Notes-up should expect an existing database to always be in `XDG_DATA_HOME/notes-up/NotesUp.db`

## Current Behavior
Notes-up loads its database from a directory that is the value of `/org/notes/notes-database`, and if a user moves their home directory Notes-up will fail to load the datebase. That's because we have the hardcoded path in the key.

**Comment by Philip-Scott** [comment]
This is currently being indirectly solved by #329 :) Hopefully this will be able to solve all these types of problems

**Comment by worldofpeace** [comment]
@Philip-Scott Totally, it's nice when you open a bug report and there's wIp feature that probably already fixes it :smile:

**Comment by Philip-Scott** [comment]
Fix has been merged in master :)
