### ISSUE TITLE
Generally unresponsive and hard to handle

### ISSUE THREAD

**Issue by dorianxonic** [Philip-Scott/Notes-up#335]
## Expected Behavior
Responsiveness.

## Current Behavior
Renaming, moving to a different notebook... basic tasks are a pain in the arse, requiring to be done several times in order to happen. 

## Steps to Reproduce (for bugs)
Use the app.

## Context
Beautiful app but very disappointing.

## Your Environment (for bugs)

- Notes-Up Version: Version from AppCentre
- OS Info: Elementary OS 5 Juno

**Comment by Philip-Scott** [comment]
Closing as duplicates of #182 #23
