### ISSUE TITLE
"[GLib-GIO] Settings schema 'org.notes' does not contain a key named 'panes-visible'"

### ISSUE THREAD

**Issue by wolframroesler** [Philip-Scott/Notes-up#342]
## Expected Behavior

After building the app from source, I expect it to run.

## Current Behavior

It crashes immediately.

```
$ G_MESSAGES_DEBUG=all ./com.github.philip-scott.notes-up
[INFO 23:17:16.657309] Application.vala:155: Notes-Up version: 2.0.0
[INFO 23:17:16.657372] Application.vala:157: Kernel version: 4.15.0-64-generic
(Notes-Up:3787): Gtk-DEBUG: 23:17:16.757: Connecting to session manager
[ERROR 23:17:16.759331] [GLib-GIO] Settings schema 'org.notes' does not contain a key named 'panes-visible'
Trace/breakpoint trap
```

## Steps to Reproduce (for bugs)

    $ sudo apt install libgranite-dev
    $ sudo apt install libgtksourceview-3.0-dev 
    $ sudo apt install libwebkit2gtk-4.0-dev
    $ sudo apt install libsqlite3-dev 
    $ sudo apt install libgtkspell3-3-dev
    $ sudo apt install libmarkdown2-dev
    $ cd /opt
    $ git clone https://github.com/Philip-Scott/Notes-up
    $ cd Notes-up
    $ mkdir build
    $ cd build
    $ cmake ..
    $ make -j4
    $ ./com.github.philip-scott.notes-up 
    [INFO 22:58:41.376101] Application.vala:155: Notes-Up version: 2.0.0
    [INFO 22:58:41.376160] Application.vala:157: Kernel version: 4.15.0-64-generic
    [ERROR 22:58:41.480277] [GLib-GIO] Settings schema 'org.notes' does not contain a key named 'panes-visible'
    Trace/breakpoint trap

## Context

Trying to build Notes-up from source because I'm planning to contribute.

## Screenshots of the Problem

n/a

## Your Environment (for bugs)

```
$ uname -a && cat /etc/os-release
Linux thinkpad 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
NAME="elementary OS"
VERSION="5.1 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1 Hera"
LOGO=distributor-logo
VERSION_ID="5.1"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic

$ git describe --tags
2.0.2-8-gba320cc
```

- Notes-Up Version: 2.0.2, commit ba320cc
- OS Info: Elementary 5.1

**Comment by wolframroesler** [comment]
By the way, Notes-up works fine when I run the version I installed via the Elementary App-Center. The error only occurs if I run the version I built from source. Thanks for any help.

**Comment by Philip-Scott** [comment]
You need to install the version from source, run sudo make install as well :)

**Comment by wolframroesler** [comment]
Works, thanks!

It was in the instructions, OK. I thought there was a way to run the version I built without overwriting the installed version. Because, during development, every now and then you're left with something that doesn't quite work as expected, you know :) Is there any way to do that, short of re-installing via App Center?

**Comment by Philip-Scott** [comment]
The reason the install is needed is because the gschema needs to be installed to be used. You could just manually install that, but you end up in the same position :) and you can always just reinstall from app center or from master once you are done :)
