### ISSUE TITLE
Black Border around the App.

### ISSUE THREAD

**Issue by edenprojectde** [Philip-Scott/Notes-up#346]
## Expected Behavior
No big black border around the app instance :)

## Current Behavior
Black Border around app.

## Possible Solution
? Add an option to disable the outcast shadow of the window

## Steps to Reproduce (for bugs)
1. Use KDE Neon
2. install the App via Flatpak
3. ???
4. Profit

## Context
```
ben@EdenTheFourthVII:~$ G_MESSAGES_DEBUG=all
ben@EdenTheFourthVII:~$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=com.github.philip-scott.notes-up com.github.philip_scott.notes-up
[INFO 18:25:39.236298] Application.vala:155: Notes-Up version: 2.0.0
[INFO 18:25:39.236340] Application.vala:157: Kernel version: 5.3.0-26-lowlatency
```
I also did try disabling the compositor for the app, and enabling it too. Both have the same result for me.

## Screenshots of the Problem
![Screenshot_20200125_181825](https://user-images.githubusercontent.com/6115966/73124747-2ddc8c80-3f9f-11ea-9de4-28403d943622.png)

## Your Environment (for bugs)
```
Linux EdenTheFourthVII 5.3.0-26-lowlatency #28~18.04.1-Ubuntu SMP PREEMPT Wed Dec 18 17:27:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
NAME="KDE neon"
VERSION="5.17"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User Edition 5.17"
VARIANT="User Edition"
VERSION_ID="18.04"
HOME_URL="http://neon.kde.org/"
SUPPORT_URL="http://neon.kde.org/"
BUG_REPORT_URL="http://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic```

- Notes-Up Version: 2.0.0
- OS Info: KDE Neon User Edition (on Kernel 5.3.0-26-lowlatency)

**Comment by yannicka** [comment]
I've the same issue with others Flatpak applications on Ubuntu. So I think it's a flatpak issue.

**Comment by edenprojectde** [comment]
@yannicka well i assume it's the glow effect on these windows, if flatpak can manipulate that to use the desktops method to produce it it(or not in some cases) would be fixable on flatpaks side.

So should this be elevated to flatpak?

Cant find an issue where this kind of behaviour is being reported.

**Comment by yannicka** [comment]
I've this issue only with elementary Flatpak applications, e.g.:

![bildo](https://user-images.githubusercontent.com/22885898/75117503-43160b00-5672-11ea-8d06-d73005d55664.png)

So i don't know where the problem is (application, Flatpak, Granite, Flatpak runtime...).

**Comment by hklaufus** [comment]
FYI: I do *not* have this issue with the Notes-up flatpak application in Fedora 31..

**Comment by edenprojectde** [comment]
@hklaufus what DE/WM do you use?

**Comment by hklaufus** [comment]
@edenprojectde Gnome Version 3.34.5

**Comment by yannicka** [comment]
Personally, on Kubuntu 20.04, I deleted my `~/.config/` folder and that fixed the problem. I probably had a bad configuration.

**Comment by edenprojectde** [comment]
I cant test it anymore i switched to Gnome. Works fine now ^^'

If nobody is reporting to this anymore idk if the issue still exists. Just to get people a heads up **to report this again** if it still happens on KDE. (i didnt test the config removal, i just needed a blank slate about 2 months ago and didnt really think about this issue anymore)

Maybe this should be closed as long as nobody else reports this.
