### ISSUE TITLE
The image is not displayed in the view tab.

### ISSUE THREAD

**Issue by bogdasar1985** [Philip-Scott/Notes-up#353]
# Problem overview.
I try to insert the image into the note using first Markdown syntax and then HTML. None of these options work.

## Expected Behavior
I need to see the image on the view tab.

## Current Behavior
I see a logo that indicates an image.

## Possible Solution
It may be possible to upload images from the Internet.

## Steps to Reproduce (for bugs)

1. Just insert `![logo](https://github.com/bogdasar1985/Conspects/blob/master/Algorithms/Images/Graph.png  "Graph")` or `<img src="https://github.com/bogdasar1985/Conspects/blob/master/Algorithms/Images/Graph.png" alt="Graph">` into note and go to the view tab.

## Screenshots of the Problem
In write mode:
https://github.com/bogdasar1985/Conspects/blob/master/Bugs(for_Notes_up_dev)/Bug_write.png

In view mode:
https://github.com/bogdasar1985/Conspects/blob/master/Bugs(for_Notes_up_dev)/Bug_view.png

## Your Environment (for bugs)

- Notes-Up Version: 2.0.2
- OS Info: Linux bogdasar-Aspire-V3-571G 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
NAME="Linux Mint"
VERSION="19.3 (Tricia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.3"
VERSION_ID="19.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tricia
UBUNTU_CODENAME=bionic

**Comment by Philip-Scott** [comment]
When inserting images from the web, make sure to put the URL for the raw image on the field instead of from a website :) 



Use this instead:

```Markdown
![Alt Text](https://github.com/bogdasar1985/Conspects/blob/master/Algorithms/Images/Graph.png?raw=true)
```

![image](https://user-images.githubusercontent.com/10786508/79092596-40e13c00-7d06-11ea-9235-aedd478baa23.png)
