### ISSUE TITLE
How to save my notes in Cloud Drive

### ISSUE THREAD

**Issue by zhandosweb** [Philip-Scott/Notes-up#354]
Hello!

I'm using Dropbox like Cloud Drive on my Elementary OS. And then I'm using Notes-up to write markdown notes for myself. 

Please, tell me. How I can save all my notes in Cloud Drive or selected another folder? Maybe there I can create a database in the selected folder, where I can store all my notes? Or something else? 

Very not convenient to export each markdown-note to Cloud Drive. I want to access all my notes in another device, using my Dropbox account. 

Sorry for bad English, believe that you understand me. And thank you for your app!

**Comment by hklaufus** [comment]
Maybe more general: 
Let user define in `Preferences` where to store the NotesUp.db

**Comment by zhandosweb** [comment]
> Maybe more general:
> Let user define in `Preferences` where to store the NotesUp.db

Ye, need something like this. And store/save all notes in selected folder.

**Comment by Philip-Scott** [comment]
Just merged in Master a way to view the files that you are using in Notes-Up, as well as the ability to have more than one "Notebook" file :)

**Comment by Jotune** [comment]
While the features added are really cool, I think they are very different from what was asked.
