### ISSUE TITLE
[FEATURE REQUEST] Create a sync with Google Keep

### ISSUE THREAD

**Issue by hklaufus** [Philip-Scott/Notes-up#356]
The idea is to add new functionality to be able to add a notebook that syncs with Google Keep.

**Comment by Philip-Scott** [comment]
Hey, thank you for the suggestion but I'm going to be closing this and the other One Note feature requests and marking them as "Out of Scope" for the project :) I just don't have the resources to do the work required to do this, but as of the new version of the app I've made it easier to work with Files from within the app!
