### ISSUE TITLE
Zero byte PDF exports on elementary OS 6 Daily.

### ISSUE THREAD

**Issue by hanaral** [Philip-Scott/Notes-up#366]
I believe it was also te case when I was using it on 5, as I never got the PDF functionality to work.
I'm **using the latest git** available, and running it in the terminal doesn't seem to output anything.

**Comment by Philip-Scott** [comment]
Sadly this is due to a limitation on how Printing to PDF works on other languages. There are instructions over at #1 that will help solve this issue for everyone using your system's language :)
