### ISSUE TITLE
New notebook marker color broken

### ISSUE THREAD

**Issue by Andrewsudarikov** [Philip-Scott/Notes-up#39]
When a new notebook is created and the marker color chosen it always switched to default black color. 
So I have to go to editing the notebook properties and selecting the color again - then it works.

**Comment by Philip-Scott** [comment]
This is a weird bug i haven't being able to reproduce. ( #4 ) 

Do you mind sharing your computer's specs, and whether you installed it from the PPA, or if you compiled it? 

Thank you! :smiley:
