### ISSUE TITLE
LATeX Plugin

### ISSUE THREAD

**Issue by luisnando** [Philip-Scott/Notes-up#42]
It would be great to have pandoc export capabilities. My notes are scientific in general, and sometimes I need to produce handouts. If I could export them into LATeX, so I could print them with a nice template like tufte-handout, that would be awesome. If you have some time, have a look at the Rmarkdown package, it works wonders already, but have it bolted into this app would be amazing. Please share a bitcoin address for donations!

**Comment by Philip-Scott** [comment]
There have being quite a few people asking for LATeX support. After some thought, I've decided to not explicitly code support for LATeX, but instead make some kind of Plugin API for the app. 

For example, let's say you want a pie chart. There could be a plugin for it were you could type something like <PieChart, 30%, 20%, 50%> and it would automatically make it for you when you clicked render. 

In this way, you could also do: <LATeX, equation here> and the latex plugin would parse it into latex for you.

This feature will be more like a 1.3 feature though, but i think it would be very useful :smiley:

**Comment by Philip-Scott** [comment]
Hey there! I'm going to close this report to clean up the bug tracker as #43 will be covering the whole plugin API 😄
