### ISSUE TITLE
Plugin API

### ISSUE THREAD

**Issue by Philip-Scott** [Philip-Scott/Notes-up#43]
# The Future is Plugins!

There should be some kind of plugin API where you could easily do things such as charts, insert websites, and even more advanced stuff like LATeX support. 
### Plugin ideas:
- [ ] Attach Documents: Use some kind of viewer like http://viewerjs.org to display PDFs, Word docs etc
- [ ] Import code: Instead of copy-pasting code, have it so you can link to the document on your computer
- [ ] LATeX
- [ ] Simple Graphs & Charts
- [x] Syntax highlighting
- [x] Insert videos without embedded code
- [x] Color chooser

**Comment by oskarkunik** [comment]
# Syntax highlighting with language detection

More than anything I'd love to see code highlighting with language detection for [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/). Cheers!

**Comment by Philip-Scott** [comment]
@oskarkunik That's definitely doable! :smiley: 

![screenshot from 2016-11-06 15 57 08](https://cloud.githubusercontent.com/assets/10786508/20042104/b358df8a-a439-11e6-9ab5-d4b6918c2e4c.png)

In the meantime though, if you want to manually add language detection you should add the folowing to your notes:

```
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/styles/default.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
</head>
```

**Comment by brian-avery** [comment]
Nice program Phillip! I've been looking for something like Notes-Up on Linux for a while. How extendable do you see the plugin system being? Do you see the ability to add a drawable area with the plugins? I.e. I have a laptop with a pen. Would I be able to create a plugin to allow me to use that pen and draw on my notebook? 

I'm teaching myself machine learning in my free time. I'm playing around with the idea of trying my hand at adding an extendable machine learning OCR plugin. I'm envisioning something where the user creates a drawable text area and writes whatever they want on it. Once they are done, they click a button, select a language (English, other languages, Latex, etc), and the plugin then converts what it can of the drawing into indexable content. Start with English of course, but design to be extendable.  I think that would be something really useful for meetings, classes, etc. Places where content is not necessarily typeable character based and needs to be added quickly.

**Comment by Philip-Scott** [comment]
@brian-avery It's definitely doable :) Plugins have the power to either insert anything at the editor, or change something for another before it starts rendering. They also currently have the ability to add a button in the editor's toolbar, so your possibilities are really limitless! I'm not sure how you could do the handwriting detection using something in GTK, but it would be really cool to see!

**Comment by tenroc** [comment]
Really nice note app, thanks a lot for your work!
Would it be possible to add the possibility to write simple tables?
Maybe using a syntax along those lines? :

          | title 1   | title 2   | title 3
title a  | cell 1a | cell 2a  | cell 3a
title b  | cell 1b | cell 2b  | cell 3b
title c  | cell 1c | cell 2c  | cell 3c

**Comment by Philip-Scott** [comment]
@tenroc You already can :) You just need to add a line:

``` title 1   | title 2   | title 3 
---------|-------------|---------
 cell 1a | cell 2a  | cell 3a 
 cell 1b | cell 2b  | cell 3b 
 cell 1c | cell 2c  | cell 3c ``` (And you don;t even need the lines at the end :wink: )

**Comment by tenroc** [comment]
Neat!
But I might be doing something wrong, however, since for me, theses lines:

![alt text](http://i.imgur.com/NrRE4yC.png)

Render like this:

![alt-text](http://i.imgur.com/btM0wU3.png)

Which as you can see isn't exactly a practical way to display a table.
I should add that I'm running a self packaged version of the git master branch as I'm currently running solus and no package was available from the repo.
That however shouldn't impact the table option since the discount version I used in the packaging process (as I understand it the one that provide the markdown implementation) was up to date and coming straight from the solus repo.
However since I'm pretty far from being comfortable with anything code, software, or software packaging related, I would really appreciate it if you could point me to anything I might be doing wrong!

Thanks again for creating such a great note app!

**Comment by Philip-Scott** [comment]
@tenroc Interesting, what stylesheet are you using? I'm using the default stylesheet and mine render like this: 

![Uploading Screenshot from 2017-01-11 20:01:45.png…]()

I did have some problems setting up the repo this time but it should be good to go now :)

**Comment by tenroc** [comment]
@Philip-Scott  Oh I've tried that with all of the included stylesheets. The screenshots were taken using the default one I think.
However, even if on yours, the alignment and spacing is definitely a lot better, there is still no cell separation lines. Is there an option to add them? Is this configurable via the CSS stylesheet?

As for the repo, as mentioned as I'm not using elementary or even ubuntu. So I never really got to interact with your ppa. I was referring in my previous post to the absence of the package from the Officials Solus repos. I guess I'll just have to keep packaging for myself, but that's alright really :) . Kind of forced me to learn how to package for the distro I'm running, and that's always a good thing to know.

**Comment by Philip-Scott** [comment]
Closing since the API has been done :)
