### ISSUE TITLE
Notes-up doesn't work correctly with HTML code

### ISSUE THREAD

**Issue by Andrewsudarikov** [Philip-Scott/Notes-up#45]
When writing some snippets of code in Notes-u, it highlights the spelling in edit mode and shows a blank page in view mode. Maybe it's a good idea to keep the script highlighted in view mode and not to try to execute it? 
[https://www.youtube.com/watch?v=_9rU2tGtmf4](url)

Oh, and remembering my prior report. This is my system configuration: 
Elementary OS Freya 0.3.2 64-bit
Processor: Quad-Core Intel Core i5-2300
Graphics: NVIDIA GF116 (GeForce GTX 550 Ti)

**Comment by Andrewsudarikov** [comment]
Oh, and remembering my prior report. This is my system configuration: 
Elementary OS Freya 0.3.2 64-bit
Processor: Quad-Core Intel Core i5-2300
Graphics: NVIDIA GF116 (GeForce GTX 55 Ti)

**Comment by Philip-Scott** [comment]
Actually, this is more of an advanced "feature" than a bug. Markdown will not parse html code, instead it will just add it into the view so you can insert custom snippets of code. 

For example, if you copy the "embedded" code of a YouTube video, it will actually add the video to your notes! 

If you wanna add the actual code as plain text, try surrounding them with triple ''' 😄

Btw, Thank you for the video! ☺️
