### ISSUE TITLE
Filename not cleaned: "/" breaks note saving

### ISSUE THREAD

**Issue by jmjr** [Philip-Scott/Notes-up#46]
Notes go missing when there is a character like " / " in the first header. Not sure if it is the only character that provokes this behavior, would be interesting.

e.g. A note that starts like this disappears after closing and reopening Notes-up:

# Issue One / Two 

Sometimes Notes-up even crashes because of that.

**Comment by Philip-Scott** [comment]
Yeah... i'm grabbing the first line and using it as the file name. I think the / is making it try to save into a different non existing directory. 

I''ll make it so it cleans up the first line from characters that could break it, for now if you could make your titles not have a '/' it would be great! :wink: 

Thank you for reporting it!

**Comment by jmjr** [comment]
That explains the behavior. Cool. Ok, sure, no problem. 

Thanks for the quick response and good work!

**Comment by Philip-Scott** [comment]
Hey there! :) The latest commit 3071a84ea3a885befe646bd700e1efc2701ed52e should have fixed the problem you're having. The PPA build will not be updated until the next full release, so if you want the fix, you should be able to pull and build 

Thank you for reporting it btw! It was something i've overlooked
