### ISSUE TITLE
Feature Request: Custom renderer (like pandoc) support ?

### ISSUE THREAD

**Issue by Menci** [Philip-Scott/Notes-up#47]
With custon renderer, we can add more features (like math equation) ourselves.

**Comment by Philip-Scott** [comment]
Yup, that is the plan, but for version 1.3 😄 I want to get the rest of the app really solid and feature complete before making a plugin API for it.

In the meantime, I'm going to close this bug as it's a duplicate of #43 . But still, thank you for making a comment 😄
