### ISSUE TITLE
Note disappears when closing the application in Edit view

### ISSUE THREAD

**Issue by voline** [Philip-Scott/Notes-up#48]
I am using Notesup in combination with Seafile and am not sure the following problem is as a result of this. 

My .notes folder is moved from its native location to the Seafile folder, with a shortcut to that folder is pasted in the native folder. Suppose I write a note "This bug is destroying my work," and close Notesup in the "edit view." Next time I open it up, the contents of the note are gone. The note file "This bug is destroying my work" shows up as a 0kb file in the file browser, and looks like this in the application;

![image](https://cloud.githubusercontent.com/assets/17718635/15921873/48ab7340-2e42-11e6-90f0-68847d2c627b.png)

**Comment by dcharles525** [comment]
I also have this issue, running Elementary OS Freya

**Comment by Philip-Scott** [comment]
So let me get this straight. You make .notes a link to a folder on SeaFile? Did you happen to move the file while the app was opened? 

Maybe the app is not playing well with the shortcut you made. 

Does this bug where notes don't save happen if you don't have the shortcut setup?

**Comment by dcharles525** [comment]
I just have the problem without any short cuts, just regular install, to clarify.

On June 9, 2016 9:42:46 AM EDT, Felipe Escoto <notifications@github.com> wrote:
>So let me get this straight. You make .notes a link to a folder on
>SeaFile? Did you happen to move the file while the app was opened? 
>
>Maybe the app is not playing well with the shortcut you made. 
>
>Does this bug where notes don't save happen if you don't have the
>shortcut setup? 
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Philip-Scott/Notes-up/issues/48#issuecomment-224898249

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Philip-Scott** [comment]
Can you guys clone master and install that? It might have being fixed already :)

**Comment by voline** [comment]
I am unable to build it. Get errors with `cmake -DCMAKE_INSTALL_PREFIX=/usr ../`

**Comment by Philip-Scott** [comment]
@voline Which errors did you get?

**Comment by voline** [comment]
Error says ;
`-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for one of the modules 'webkit2gtk-4.0;webkit2gtk-3.0'
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:367 (message):
  None of the required 'webkit2gtk-4.0;webkit2gtk-3.0' found
Call Stack (most recent call first):
  CMakeLists.txt:34 (pkg_search_module)


-- checking for modules 'granite>=0.3;gtksourceview-3.0>=3.10;gthread-2.0;gtk+-3.0>=3.9.10'
--   package 'granite>=0.3' not found
--   package 'gtksourceview-3.0>=3.10' not found
--   package 'gthread-2.0' not found
--   package 'gtk+-3.0>=3.9.10' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  CMakeLists.txt:39 (pkg_check_modules)


-- checking for modules 'granite>=0.3;gtksourceview-3.0;gtk+-3.0;webkit2gtk-4.0;discount'
--   package 'granite>=0.3' not found
--   package 'gtksourceview-3.0' not found
--   package 'gtk+-3.0' not found
--   package 'webkit2gtk-4.0' not found
--   package 'discount' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  CMakeLists.txt:62 (pkg_check_modules)


CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Vala (missing: VALA_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindVala.cmake:55 (find_package_handle_standard_args)
  CMakeLists.txt:79 (find_package)


-- Configuring incomplete, errors occurred!
`

**Comment by Philip-Scott** [comment]
@voline Can you start tryping `sudo apt-get install libwebkit2gtk-` and try to autocomplete? :) You need the one ending with `-dev`. And also do the same with libwebkit2gtk

**Comment by voline** [comment]
@Philip-Scott I am not to sure what you mean. When I try those commands with the version numbers, I get `E: Unable to locate package libwebkit2gtk-3.0-25-dev E: Couldn't find any package by regex 'libwebkit2gtk-3.0-25-dev' 

So I am not quite sure how to retrieve them.

**Comment by dcharles525** [comment]
my issue has been solved, thank you.

**Comment by Philip-Scott** [comment]
@dcharles525 The newest branch solved it, or did you do something on your end? If the branch solved it i'll be closing the bug report :smile:
