### ISSUE TITLE
Custom theme for editor part

### ISSUE THREAD

**Issue by Defman21** [Philip-Scott/Notes-up#50]
I want to see an ability to create your own themes for editor part.

**Comment by Philip-Scott** [comment]
AFAIK, those have to be installed on the system, and cannot be modified by the user. The ones installed can be chosen from the preferences dialog, but a full theme editor is a bit out of scope and would just complicate things. Still, thank you for the feedback :smiley:

**Comment by Defman21** [comment]
Hmm okay, thanks.
