### ISSUE TITLE
Files created in-source

### ISSUE THREAD

**Issue by flopp** [Philip-Scott/Notes-up#54]
When performing an out-of-source build, e.g.

```
mkdir build
cd build
cmake ..
make
cd .. 
```

files in the source directories are changes/created (`src/config.vala` and various files in `deps/discount`). I would expect that the source directories are not touched and instead all files are generated within the `build` directory.

**Comment by Philip-Scott** [comment]
Yeah, i agree that the deps/discount files is messy. I'm no expert with CMake but i'll see what i can do about it :) 
The config.vala appears on the rest of the elementary projects though, so maybe that works as intended (?)

**Comment by demonpig** [comment]
I have a PR where a .gitignore file is added. I think that would resolve this issue.

**Comment by demonpig** [comment]
I think this has been solved via the recent merge of the .gitignore list.

Simply:

    mkdir build && cd build

    cmake ..

    make

**Comment by Philip-Scott** [comment]
Mmm not really, It's still adding files on deps/discount. The expected behaviour is that everything gets added inside of `build`. But it was a good middle step :)

**Comment by demonpig** [comment]
I am working on configuring CMake to download discount directly from the **[source](http://www.pell.portland.or.us/~orc/Code/discount/)**. The version of discount being downloaded will not change. So version 2.2.0 will be downloaded. Once the download finished, CMake will then compile discount from there. 

Right now I have it working on my machine but am going to test a build on Loki VM.

**Comment by demonpig** [comment]
@Philip-Scott Do you think its wise to have CMake download discount from [Github](https://github.com/Orc/discount/archive/v2.2.2.tar.gz) or should CMake use git-submodules? I am conflicted between both options. I am not too familiar with git-submodules but I can learn more about them.

**Comment by Philip-Scott** [comment]
If i understand submodules correctly, i think using them might be safer since i could at least make sure that the release is working properly with the module i'm targeting instead of having it download automatically (and potentially breaking)

**Comment by demonpig** [comment]
OK. I am going to explore using that instead of downloading. I was having second thoughts about downloading the library as there was no sha256 checksum provided with the download. People would have to trust that the library was not modified.
