### ISSUE TITLE
No way to have h1, h2, etc. titles

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [Philip-Scott/Notes-up#57]
I've noticed that there isn't an option to have a title, subtitle etc. by the controls, but it's available if written manually. Have you considered this? I'm willing (albeit inexperienced) to work on this, if you tell me how you want it. I've already succeeded in adding a button that adds h1, /h1 tags in the same way that other tags work, but I think that some kind of spinner or something that would group those different title sizes would be better...

**Comment by Philip-Scott** [comment]
I've added a help section on the editing view in https://github.com/Philip-Scott/Notes-up/commit/ca074d07fca04b6505b526e6f2fc29ecaea3fb86 

It's not really this item on the toolbar, but it will still introduce new people on how to use it!
