### ISSUE TITLE
Characters not displaying correctly. (Possibly codification error)

### ISSUE THREAD

**Issue by andbuitra** [Philip-Scott/Notes-up#61]
The app is not displaying accents 
![captura de pantalla de 2016-09-01 07 32 43](https://cloud.githubusercontent.com/assets/5218132/18167460/4d8a8c0a-7016-11e6-827d-df2b52431d56.png)

Maybe the app encoding is not UTF-8?

**Comment by Philip-Scott** [comment]
Oh i'll look into it! might be a problem with the translation since accents are currently supported. 

Spanish right? :smiley:

**Comment by andbuitra** [comment]
@Philip-Scott Yes, it is spanish. 

I thought it was related to UTF-8 encoding (common issue on web development) and tried to search for the xml to change the encoding but I have no experience at all with Vala

**Comment by Philip-Scott** [comment]
That should fix the problem :) Thank you for reporting it! 

I'll also be updating the rest of the spanish translations
