### ISSUE TITLE
Save content for reinstall

### ISSUE THREAD

**Issue by psylock** [Philip-Scott/Notes-up#63]
I'm gonna reinstall Loki soon, how can i save my Notes Up content for a new Notes Up installation ?

Thanks,

**Comment by Philip-Scott** [comment]
Your notes should be saved to ~/.notes/ :smile: You can just copy that folder, and place it again after re-installation

BTW: If you install Loki with two different partitions (One for `/` and one for `/home`), you can just wipe the `/` without loosing your files in `/home`
