### ISSUE TITLE
Spell Checking?

### ISSUE THREAD

**Issue by eprozium** [Philip-Scott/Notes-up#64]
Hi,

Any chance getting spell checking functionality into Notes-up?

Thank you.

**Comment by OriginalFannibal** [comment]
Could the `spell checker` extension for Scratch be of any use here?

**Comment by proxycyber** [comment]
Any updates on this? Spell check would be super useful.

**Comment by Philip-Scott** [comment]
No, I've decided not to add this. Sorry

**Comment by Philip-Scott** [comment]
Nah, i'm joking :smile: 

It's been just pushed to master: https://github.com/Philip-Scott/Notes-up/commit/2f566324c5a63bb3bf597bdc1008279b1d103ea0 and will be out on AppCenter soon :)

**Comment by proxycyber** [comment]
Lol! That's great. :) Can't wait for this.
