### ISSUE TITLE
Tray icon for Loki

### ISSUE THREAD

**Issue by Kalt78** [Philip-Scott/Notes-up#65]
Are there any plans in the future?

**Comment by Philip-Scott** [comment]
@Kalt78 What would be the advantage to have a Tray Icon? 

https://elementary.io/docs/human-interface-guidelines#does-your-app-need-an-indicator

**Comment by Kalt78** [comment]
It's convenient for me. I'm used to using Tomboy.

**Comment by Philip-Scott** [comment]
To be honest, the new Tray system isn't really made for these types of apps. System indicators should really be used to indicate things about your system :wink: If you use an specific feature of it, i could add it as an action on the dock icon. But for now, i'm going to mark it as Wont Fix
