### ISSUE TITLE
Syntax highlight for code spinnets

### ISSUE THREAD

**Issue by pulgalipe** [Philip-Scott/Notes-up#69]
I would like to have syntax highlight for code snippets on a note, it's one of the most basic features from a markdown editor and this is what's missing for this app become even better.

Thanks for support and this great app.

**Comment by Philip-Scott** [comment]
I'm definitely planning on adding that once the plug-in system is out :) I've been super busy at school but hopefully after next week i'll have time again! 

In the mean time, i wrote about how to add Syntax highlighting on issue #43
