### ISSUE TITLE
Online syncing

### ISSUE THREAD

**Issue by ghost** [Philip-Scott/Notes-up#70]
Is there any possibility of adding syncing via SimpleNote or other online note syncing service?

Thank you.

**Comment by richardwonka** [comment]
Evernote and Google Keep come to mind...

it _would_ be a fantastic feature, even if it's just the possibility to import for a start. :)

**Comment by ajiyakin** [comment]
I think it would be easy if the notes stored in `.md` file :thinking:

**Comment by Philip-Scott** [comment]
@ajiyakin it's actually a database... So it's not that trivial

**Comment by LievenHanssen** [comment]
I use SpiderOak to synchronize all my files, so for me and anyone who is using Dropbox or Box or any other similar cloud service, being able to choose where you'd want to store this database in the _Preferences_ menu would be enough to easily synchronize our notes, without having to use dconf-editor.

**Comment by truscellino** [comment]
I guess that would be a massive undertaking, but what about web-based editing (like evernote, laverna...)? There might be other potential users like me who don't have permanent access to their elementary OS machine all the time, which means they can't access their notes? At least for users who run their own web servers and could host their own sessions...

**Comment by Philip-Scott** [comment]
@truscellino The database schema is there, and also the code with how everything works. If anyone wants to take up that challenge, i will gladly help and explain them how the app and the database works :)

**Comment by dcharles525** [comment]
Maybe just a option to change the save path of the database and save it to a synced folder of your choosing?

I would be willing to dedicate a little time to building a server side API if @Philip-Scott rather go the super custom route instead of having to rely on other services.

**Comment by Philip-Scott** [comment]
@dcharles525 That's very kind of you, but sadly only half of the problem. It would still need to be secure, buy and pay for hosting, and make sure that the server never falls because it could cost people their information. 

There's already an option to set the save path, you can access and change it from dconf on /org/notes :)

**Comment by dcharles525** [comment]
Digitalocean might sponsor the project and handout a free VPS. They sponsor other projects I know. As for the server maintenance and such might be a difficult task to handle if your user base exploded ( which I know it will/is :) ).

I was thinking a setting in the UI where you could redirect the saving location.

**Comment by Philip-Scott** [comment]
@dcharles525 about the saving location, you might be interested in following #148. I want to add it to the settings dialog, but i'm still not sure on the best way to do so without allowing the user to "loose" their notes

**Comment by sschuhmann** [comment]
Maybe syncing with smtp accounts like apple notes for example would be a good starting point. 
As far as i know evolution does this already, so it might be easy to implement

**Comment by Nine-H** [comment]
I had a whinge a while ago about switching to databases over flat files/meta.xml. I liked the idea of using git to keep everything synced and track changes. Maybe throw it to the brains trust on slack https://elementarycommunity.herokuapp.com/ because cloud notes would be really sick.

**Comment by aljelly** [comment]
One of the main features of [Standard Notes](https://standardnotes.org/) is free built in end-to-end encrypted sync (the client is Electron).

The whole thing is open source and documented. If you were to implement compatibility with Standard Notes' [Standard File](https://standardfile.org/#intro) library, you could probably get the client to connect with the default Standard Notes server. Or you could also host your own Standard File server.

(There's a [client development guide](https://github.com/standardnotes/doc/blob/master/Client%20Development%20Guide.md))

**Comment by sschuhmann** [comment]
Nextcloud is providing a note synchronization via the [notes](https://github.com/nextcloud/notes) app. This app also offfers a open rest implementation to work with the notes. 

Bijiben alredy has some basic integration for NextCloud notes working, so some of their work could be reused.
