### ISSUE TITLE
Not able to build Notes-Up on elementary Freya

### ISSUE THREAD

**Issue by demonpig** [Philip-Scott/Notes-up#74]
When trying to build the updated the Notes-Up application, I am getting the following error message:
```
/Notes-Up/build/src/Widgets/Viewer.c:687:51: error: unknown type name ‘WebKitNavigationAction’
 static GtkWidget* __lambda5_ (ENotesViewer* self, WebKitNavigationAction* navigation_action);
                                                   ^
/Notes-Up/build/src/Widgets/Viewer.c:689:79: error: unknown type name ‘WebKitNavigationAction’
 static GtkWidget* ___lambda5__webkit_web_view_create (WebKitWebView* _sender, WebKitNavigationAction* navigation_action, gpointer self);
                                                                               ^
Viewer.c:771:51: error: unknown type name ‘WebKitNavigationAction’
Viewer.c:794:79: error: unknown type name ‘WebKitNavigationAction’
/Notes-Up/src/Widgets/Viewer.vala: In function ‘enotes_viewer_connect_signals’:
/Notes-Up/src/Widgets/Viewer.vala:99:72: error: ‘___lambda5__webkit_web_view_create’ undeclared (first use in this function)
         create.connect ((navigation_action)=> {
                                                                        ^
/Notes-Up/src/Widgets/Viewer.vala:99:72: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/notes-up.dir/src/Widgets/Viewer.c.o] Error 1
make[1]: *** [CMakeFiles/notes-up.dir/all] Error 2
make: *** [all] Error 2
```
From what I can gather, `WebKitNavigationAction` only exists in webkit2gtk-4.0. I saw in the CMakeLists.txt file that there is a check for both version 3 and 4 of webkit2gtk. But when adding the dependencies to the compilers, ```webkit2gtk-4.0``` is specified. Below is a link to what I am referring to.

[Notes-Up CMake File](https://github.com/Philip-Scott/Notes-up/blob/master/CMakeLists.txt#L47+L65)

**Comment by Philip-Scott** [comment]
To be honest, i don't think i'll be officially supporting Freya anymore. (Loki is pretty good and i don't really have the time to make sure it supports previos versions of the OS) 

But if you really want to build it yourself it, try removing this block of code: https://github.com/Philip-Scott/Notes-up/blob/master/src/Widgets/Viewer.vala#L104 :) That should do the trick
