### ISSUE TITLE
Regarding translations

### ISSUE THREAD

**Issue by febrezo** [Philip-Scott/Notes-up#77]
I'm not sure on where to localize the appllication in Launchpad or here. It seems that this repository is more active than the Launchpad one. Is this correct? Which is the desired approach to perform the localizations?

**Comment by Philip-Scott** [comment]
Yeah, this is actually the main repo. I only use launchpad for building.

You could use the .po inside the /po directory, if the file for your language isn't generated (Or if it's outdated) you can run `make pot` and it will generate those for you :)
