### ISSUE TITLE
Notes preview pane does not render markdown

### ISSUE THREAD

**Issue by voline** [Philip-Scott/Notes-up#9]
![image](https://cloud.githubusercontent.com/assets/17718635/13594413/3cb1a07a-e52a-11e5-9d9a-014ddef5cc1b.png)

The preview pane ought to render markdown edited text as well, instead of displaying the raw text.

**Comment by Philip-Scott** [comment]
Im not sure if either allow markdown, or just remove all markdown tags from it. But yes, it's a bug ☺️ 

Btw, there's no need for the <br> Tags if you need a line jump, you can either put an empty line between that, and the next paragraph, or put two spaces at the end 😉

**Comment by voline** [comment]
Simplenote formats the preview like the main text, which is useful. For example, adding emphasis to author names. Either the preview ought to allow markdown or implement the formatting from the main text some other way. 

The notes are old ones I copy pasted from another program. Didn't know all of markdown when I wrote them. Thanks anyway!

No problem, the application is great work. Cannot tell you how many hours I have wasted over finding a proper note program.

**Comment by Philip-Scott** [comment]
simplenote is a webapp, so it's very easy for them to just display the full markdown text.....  

I can implement it so it allows the simple ones (bold, italics, underline, and strikethough) on the preview. Things like quotes, the headers or links i won't allow though, but it should be fine that way :)

**Comment by voline** [comment]
Yup, should be good!

**Comment by Philip-Scott** [comment]
On the newest commit (3071a84ea3a885befe646bd700e1efc2701ed52e) i added support for very simple markdown such as bold and italics :) The more things i add support for it, the slower it will get, but i think those two are the more used 

PPA won't be updated until the end of the Milestone, but you can always clone and build the newest release manually  :)

**Comment by voline** [comment]
Thank you very much! I will wait for the milestone. Just less tedious.
